- workflows/wf_snippy_variants.wdl
**Add Bam and Bai outputs to Snippy workflow**
This PR adds the bam and bai file outputs to the snippy variants workflow.
Outputs added:
snippy_bam
snippy_bai
> added snippy bam+bai to wf output

- .dockstore.yml
- tasks/task_nullarbor.wdl
- workflows/wf_nullarbor.wdl
**This PR adds the Nullarbor workflow**
The nullarbor workflow is a pipeline to generate complete public health microbiology reports from sequenced isolates.
**Limitations**
This workflow only supports Illumina paired-end sequencing data. The entire pipeline is contained within a single task which reduces efficiency by restricting parallelization to that which may occur on a single VM.
**This workflow operates on SET LEVEL data tables. A set of samples must be passed as the input, but certain analyses will be performed on each sample and then additional analyses will be performed on the entire set of samples**
**The following steps are performed on each isolate:**
Clean reads
(Trimmomatic)
Species identification
(Kraken2)
De novo assembly
(SKESA, SPAdes, Megahit, …
> Fja add nullarbor dev

- tasks/gene_typing/task_snippy_variants.wdl
Last commit broke TheiaEuk with changes to snippy_variants. This fixed it.
> fixed snippy_variants so as to not break theiaeuk

- workflows/utilities/wf_read_QC_trim_ont.wdl
This PR adds the `rasusa` task from `task_rasusa.wdl` to the `wf_read_QC_trim_ont.wdl` workflow
> Add rasusa to wf_read_QC_trim_ont

- tasks/gene_typing/task_tiptoft.wdl
tested successfully w miniwdl. Have not tried tweaking the multitude of optional parameters yet (I tested with default values only), but should be OK
> adds tiptoft WDL task

- tasks/utilities/task_kmc.wdl
- workflows/utilities/wf_read_QC_trim_ont.wdl
> add kmc to workflow for genome size estimation

- tasks/assembly/task_dragonflye.wdl
- workflows/theiaprok/wf_theiaprok_ont.wdl
This PR adds the dragonflye task and integrates it into the  theiaprok_ont workflow
> Add dragonflye task to theiaprok_ont workflow

- tasks/phylogenetic_inference/task_snp_sites.wdl
- workflows/phylogenetics/wf_snippy_tree.wdl
~~Setting as a draft while development and testing are underway. Will update soon.~~ 
This PR includes a new option `core_genome` that calls [snp_sites](https://github.com/sanger-pathogens/snp-sites) to reduce the MSA to the core SNPs. Therefore, the workflow now has 4 different possible paths depending on the `core_genome` and `use_gubbins` option combinations:
- run [gubbins ](https://github.com/nickjcroucher/gubbins) and [snp_sites](https://github.com/sanger-pathogens/snp-sites) if both `use_gubbins` and `core_genome` are set to `true` (default behaviour)
- only run [gubbins ](https://github.com/nickjcroucher/gubbins) if  `use_gubbins` is set to `true` and `core_genome` is set to `false`
- only run [snp_sites](https://github.com/sanger-pathogens/snp-sites) if  `use_gubbins` is set to …
> Rework Snippy_Tree wf to include core option

- tasks/assembly/task_ivar_variant_call.wdl
- tasks/utilities/submission/task_mercury_file_wrangling.wdl
- workflows/theiacov/wf_theiacov_illumina_pe.wdl
- workflows/theiacov/wf_theiacov_illumina_se.wdl
- workflows/utilities/wf_ivar_consensus.wdl
This PR makes sure that all changes made in PHVG v2.3.2 are included in PHB.
Please see PHVG v2.3.2 release notes.
This was not tested locally.
Tests are ongoing here: 
https://app.terra.bio/#workspaces/cdc-terra-resources/Theiagen_Wright_SC2_Sandbox/job_history/98d039ff-6f0b-4ecf-9c6a-20dda48b9859
https://app.terra.bio/#workspaces/cdc-terra-resources/Theiagen_Wright_SC2_Sandbox/job_history/d94cbb6d-cae3-425e-b6b9-b83b9441080e
> PHVG v2.3.2 concordance

- tasks/phylogenetic_inference/task_ksnp3.wdl
- tasks/utilities/task_summarize_data.wdl
- workflows/phylogenetics/wf_core_gene_snp.wdl
- workflows/phylogenetics/wf_ksnp3.wdl
- workflows/phylogenetics/wf_mashtree_fasta.wdl
- workflows/phylogenetics/wf_snippy_streamline.wdl
- workflows/phylogenetics/wf_snippy_tree.wdl
This PR:
1. updates kSNP3 to adjust assemblies to match the expected naming convention, 
2. checks if a core SNP matrix was produced after running kSNP3, and if not, skips the subsequent workflow steps that use the core SNP matrix, and 
3. adds a new filtered metadata file made in the summarize_data task to all phylogenetic workflows
Changes 1 and 2 were made in response to errors encountered, and change 3 was made due to request.
No new inputs have been added.
Changes 1 and 2 add two new outputs for kSNP3:
1. a file called `ksnp3_input` for the kSNP3 task that lists the name of the assembly files per sample (to check the updated file names)
2. a string that either says "The core SNP matrix was produced" or "The core SNP matrix could not be produced"
Change 3 creates a new output for all …
> kSNP3 updates and a new metadata output for phylogenetic workflows

- tasks/utilities/task_validate.wdl
> allow not present columns in validation criteria to be ignored

- tasks/quality_control/task_artic_guppyplex.wdl
- tasks/species_typing/task_quasitools.wdl
- workflows/theiacov/wf_theiacov_ont.wdl
Turns out when I squished quasitools, I did not squish all bugs. I had a conditional that did the opposite of intended which wasn't ideal.
There's also another issue regarding the ONT optional parameter, which caused failures but rearranging the variables fixed it.
I also updated the artic prefix to say HIV instead of SC2 in the instance where HIV is used instead.
Context? Over-eager squishing. Rationale? Fix squish.
I'm also running into a consensus
No changes.
No changes.
Not tested locally.
[Illumina PE](https://app.terra.bio/#workspaces/cdc-terra-resources/Theiagen_Wright_SC2_Sandbox/job_history/28b5fcae-3333-4322-9d3a-74c8d67008a3)
[ONT](https://app.terra.bio/#workspaces/cdc-terra-resources/Theiagen_Wright_SC2_Sandbox/job_history/97c98f44-256a-4ed2-9b34-98da9d773214)
Pull Request …
> Quasitools Bug Discovery and Destruction

- tasks/species_typing/task_tbprofiler_output_parsing.wdl
> CDPH TBProfiler iteration - Sage

- tests/workflows/theiacov/test_wf_theiacov_clearlabs.yml
- tests/workflows/theiacov/test_wf_theiacov_fasta.yml
- tests/workflows/theiacov/test_wf_theiacov_ont.yml
Updated theiacov GHA tests for v1.0.0
I've loosened some tests to check the files contain a string instead of strict MD5 tests. Although for some tests where a version number is generated I left those as MD5 checks and updated the MD5
> update theiacov GHA tests for v1.0.0

- tasks/utilities/task_summarize_data.wdl
… (#103)
* cast entire table as string
* optional id column
* finish id_column_name
> Update theiameta to main

- tasks/phylogenetic_inference/task_ksnp3.wdl
- workflows/phylogenetics/wf_ksnp3.wdl
Closes #121 
Two main changes are implemented in this PR:
- The *_SNPs_all file from kSNP3 is now exposed an a workflow output 
- The option to pass this *_SNPs_all file is now provided, allowing the run to append new files to an existing tree (no new kmers are computed)
This option allows for sequences to be appended to an existing tree, instead of recomputing the entire tree with the full dataset. During the addition, kSNP3 only looks for the old set of SNPs in the new genomes, so the total number of SNPs remains the same. Additionally, annotation doesn't work with the genome addition function. 
New input (optional):
- previous_ksnp3_snps
New output:
- ksnp3_snps
Skipped
- Test exposing _SNPs_all file in a 5 DENV sequence tree building: …
> Add option to append current kSNP3 run to an existing tree

- tasks/taxon_id/task_nextclade.wdl
Closes #113 
According to [the nextclade documentation](https://docs.nextstrain.org/projects/nextclade/en/stable/user/input-files.html#gene-map), the input variable gene_annotations needs to be a GFF3 file, _not_ a JSON, which is how we currently describe it. I've corrected this.
https://app.terra.bio/#workspaces/cdc-terra-resources/Theiagen_Wright_SC2_Sandbox/job_history/d00f503c-5850-472a-9322-f48d538f93e6
> Rename variable in nextclade

- tasks/utilities/task_augur_utilities.wdl
Closes #133 
Changed default extension for the merged-metadata output to `.tsv` instead of `.txt`.
Auspice.us requires either `.tsv` or `.csv`. 
Merged metadata output now has the .tsv extension
I did not test this, because nothing in the code changed except for two letters in a file extension
> change file extension

- tasks/alignment/task_minimap2.wdl
- tasks/quality_control/task_pilon.wdl
- tasks/quality_control/task_readlength.wdl
- tasks/utilities/task_parse_mapping.wdl
> update container to use google registry

- tasks/alignment/task_minimap2.wdl
- tasks/assembly/task_metaspades.wdl
- tasks/quality_control/task_pilon.wdl
- tasks/quality_control/task_readlength.wdl
- tasks/utilities/task_parse_mapping.wdl
> Im metagenomics workflow

- tasks/utilities/task_broad_terra_tools.wdl
- tests/workflows/theiaprok/test_wf_theiaprok_illumina_pe.yml
- tests/workflows/theiaprok/test_wf_theiaprok_illumina_se.yml
- workflows/theiaprok/wf_theiaprok_fasta.wdl
- workflows/theiaprok/wf_theiaprok_illumina_pe.wdl
- workflows/theiaprok/wf_theiaprok_illumina_se.wdl
- workflows/theiaprok/wf_theiaprok_ont.wdl
- workflows/utilities/wf_merlin_magic.wdl
Closes #145 
As requested by ORPH, the kleborate_virulence_score  is now exposed as output of kleborate. Additionally, the kleborate_resistance_score has also been exposed.
Requested by ORPH
N/A
N/A
Two new outputs:
- kleborate_virulence_score 
- kleborate_resistance_score 
Not tested locally
- TheiaProk_Illumina_PE_PHB: https://app.terra.bio/#workspaces/theiagen-validations/Theiagen_Mendes_Sandbox/job_history/9e31835b-df5f-49ae-8a8f-b514d5d6ff5d
- TheiaProk_Illumina_SE_PHB: https://app.terra.bio/#workspaces/theiagen-validations/Theiagen_Mendes_Sandbox/job_history/43a90a54-69ec-4050-8733-4fb07e1df955
- TheiaProk_FASTA_PHB: https://app.terra.bio/#workspaces/theiagen-validations/Theiagen_Mendes_Sandbox/job_history/aba004b1-7de8-4611-801e-f94b3c64d323
> [TheiaProk] expose kleborate_virulence_score and kleborate_resistance_score 

- tasks/phylogenetic_inference/task_iqtree2.wdl
- workflows/phylogenetics/wf_snippy_tree.wdl
Closes #143 
- sets `core_genome` to true in the Snippy_Tree workflow
- removes the `core_genome` input in the iqtree2 task 
- removes the conditional section in the iqtree2 task that selects a model based on its value; will now default to model finder unless the user provides a model
The `core_genome` variable had previously used to both determine if core genome analysis should proceed _and_ set the iqtree2 model. This dual function was confusing, and understandably led to confusion. 
In addition, our documentation indicated that it was set to true by default when this was not the case, which led to confusing & inaccurate result interpretation. Thanks to @sam-baird for opening this issue!
The optional input of `core_genome` in the Snippy_Tree workflow now has a default value of true.
The …
> Snippy_Tree `core_genome` default value

- tasks/phylogenetic_inference/task_lyveset.wdl
I created `cjk-lyveset-fastq-parsing` branch off of `cjk-lyveset-params` so that I don't disrupt anyone using this branch in Terra
This PR just merges the changes back into `cjk-lyveset-params` and I will wait until I've tested in Terra.
Don't think this will require approval, I'll just merge myself.
> lyveset fastq parsing

- tasks/assembly/task_dragonflye.wdl
- tasks/quality_control/task_screen.wdl
- tests/workflows/theiacov/test_wf_theiacov_illumina_pe.yml
- tests/workflows/theiacov/test_wf_theiacov_illumina_se.yml
- tests/workflows/theiacov/test_wf_theiacov_ont.yml
- workflows/theiacov/wf_theiacov_illumina_se.wdl
- workflows/theiacov/wf_theiacov_ont.wdl
- workflows/theiaprok/wf_theiaprok_illumina_se.wdl
- workflows/theiaprok/wf_theiaprok_ont.wdl
Reverts theiagen/public_health_bioinformatics#165
> Revert "Output Dragonflye GFA & modify read screen in TheiaProk_ONT"

- tasks/assembly/task_dragonflye.wdl
- tasks/quality_control/task_screen.wdl
- tests/workflows/theiacov/test_wf_theiacov_illumina_pe.yml
- tests/workflows/theiacov/test_wf_theiacov_illumina_se.yml
- tests/workflows/theiacov/test_wf_theiacov_ont.yml
- workflows/theiacov/wf_theiacov_illumina_se.wdl
- workflows/theiacov/wf_theiacov_ont.wdl
- workflows/theiaprok/wf_theiaprok_illumina_se.wdl
- workflows/theiaprok/wf_theiaprok_ont.wdl
Closes #158 and #157 
- Outputs the GFA from Dragonflye
- Introduces new optional Boolean variable `skip_mash` which will skip the mash sketch genome size estimation in the read screen
> Smw dragonflye screen dev

- tasks/taxon_id/task_kraken2.wdl
- tests/workflows/theiaprok/test_wf_theiaprok_illumina_pe.yml
- tests/workflows/theiaprok/test_wf_theiaprok_illumina_se.yml
This adds a simple fix to make Kraken2_SE_PHB functional
When Kraken2 runs with just SE data, the reads are outputted by default to `classified#.fastq.gz` and `unclassified#.fastq.gz` instead of the expected  `classified_1.fastq.gz` and `unclassified_2.fastq.gz`.
I've also made  `classified_2.fastq.gz` and `unclassified_2.fastq.gz` outputs optional on the `kraken2_standalone` task.
N/A
N/A
Tested on commit id b32bbbe97fe023b4d520af509d674c157c642a2a: https://app.terra.bio/#workspaces/theiagen-validations/Theiagen_Mendes_Sandbox/job_history/0151db79-ed5d-4321-aad2-65b432e1a403
> Fix kraken2_standalone for SE data

- tasks/utilities/task_kmc.wdl
- workflows/theiaprok/wf_theiaprok_ont.wdl
- workflows/utilities/wf_read_QC_trim_ont.wdl
This simple PR changes the variable type of KMC's est_genome_size to Int instead of String. 
Nothing was changed. 
N/A
est_genome_size is now `Int`
> Patch theiaprok ont - change est_genome_size to Int

- tasks/species_typing/task_ts_mlst.wdl
- tasks/utilities/task_broad_terra_tools.wdl
- tests/workflows/theiaprok/test_wf_theiaprok_illumina_pe.yml
- tests/workflows/theiaprok/test_wf_theiaprok_illumina_se.yml
- workflows/theiaprok/wf_theiaprok_fasta.wdl
- workflows/theiaprok/wf_theiaprok_illumina_pe.wdl
- workflows/theiaprok/wf_theiaprok_illumina_se.wdl
- workflows/theiaprok/wf_theiaprok_ont.wdl
One task has been updated:
- `ts_mlst`
- Update docker container to `us-docker.pkg.dev/general-theiagen/staphb/mlst:2.23.0-2023-08` with updated DB as of August 2023
- Expose docker container on the datatable 
For `ts_mlst`, the new docker contains an updated database of [PubMLST](https://pubmlst.org/) as of August 2023. With this change, we aim to improve the accuracy of the Sequence Types called. 
N/A
N/A
New output created:
- `ts_mlst_docker` for the TheiaProk suite of workflows. 
Tests passed locally with `miniwdl` for each individual task. 
Tests under way... 
> update ts mlst docker (August 2023)

- tasks/species_typing/task_tbprofiler.wdl
- workflows/utilities/wf_merlin_magic.wdl
> TBDB with varpipe

- tasks/utilities/task_kmc.wdl
> add -n to echo command in kmc to avoid new line

- tasks/quality_control/task_ncbi_scrub.wdl
> revert ncbi scrub changes to commid id 4e0fa54cb

- tasks/quality_control/task_screen.wdl
- tests/workflows/theiaprok/test_wf_theiaprok_illumina_pe.yml
- tests/workflows/theiaprok/test_wf_theiaprok_illumina_se.yml
Closes #206 
The current implementation is not calculating the proportion of reads correctly, and the reported error message doesn't reflect the defined parameter correctly. This has been fixed to reflect the changes made in PHBG https://github.com/theiagen/public_health_bacterial_genomics/pull/180/files
N/A
N/A 
N/A
N/A
Not tested locally.
~~Tests underway~~ 
Tested on a mixed sample (not matching forward and reverse read files): https://app.terra.bio/#workspaces/theiagen-validations/Theiagen_Scribner_Sandbox/job_history/d894f237-af78-40b2-a5db-52868e3f31c4
> Fix bugs in read proportion calculation - read_screen task

- .github/PULL_REQUEST_TEMPLATE.md
- workflows/standalone_modules/wf_kraken2_pe.wdl
This adds an additional section to the PR template that indicates what scenarios the user should test
None
Sometimes it's hard to think of all of the different scenarios that need to be tested as a reviewer. The author of the PR should know what sort of edge-cases might need testing
No change
No change
No change
No change
No change
- ~[] The workflow/task has been tested locally and on Terra~
> Add additional section to the PR template

- tasks/quality_control/task_pilon.wdl
This PR changes the following defaults for the Pilon task
- CPU 4 -> 8
- Memory 8 -> 32
TheiaMeta_Illumina_PE is the only affected workflow.
Pilon task is used in the metaspades_assembly sub-workflow. 
N/A
N/A
N/A
N/A
N/A
> TheiaMeta - Update Pilon defaults (cpu and memory)

- tasks/phylogenetic_inference/task_ksnp3.wdl
- tasks/taxon_id/task_midas.wdl
- tests/workflows/theiaprok/test_wf_theiaprok_illumina_pe.yml
- tests/workflows/theiaprok/test_wf_theiaprok_illumina_se.yml
- workflows/phylogenetics/wf_ksnp3.wdl
- workflows/utilities/wf_merlin_magic.wdl
> Enable TBProfiler parameter changes

- tasks/taxon_id/freyja_utilities/task_freyja_dashboard.wdl
- tasks/taxon_id/freyja_utilities/task_freyja_plot.wdl
- tasks/taxon_id/freyja_utilities/task_freyja_update.wdl
- tasks/taxon_id/task_freyja_one_sample.wdl
~~docker image does not exist yet, workflow will fail. Currently waiting for StaPH-B to deploy the docker image~~
~~Will reply back once the docker image is on our GAR.~~
Docker image is now available at: `us-docker.pkg.dev/general-theiagen/staphb/freyja:1.4.8`
**I have not tested the updated freyja docker image in Terra - can someone with more experience with these workflows test these out?**
Closes #265 
Updates the default docker image for 4 WDL tasks to use freyja 1.4.8
I'm not sure, but I'm assuming all Freyja-related workflows
> update default freyja docker image to 1.4.8 for multiple tasks

- tasks/utilities/task_czgenepi_wrangling.wdl
- workflows/utilities/wf_czgenepi_prep.wdl
Closes #284 
As requested by users who demoed this workflow, the following changes have been implemented:
- an organism specification, since mpox and SARS-CoV-2 require different metadata parameters
- change the String input `sample_is_private_column_name` to be a Boolean `is_private`
- change the GISAID ID to be the GISAID Virus Name and generated from the `private_id` column automatically
Workflows: `workflows/utilities/wf_czgenepi_prep.wdl`
Tasks: `tasks/utilities/task_czgenepi_wrangling.wdl`
Automatically generating the GISAID virus name may lead to increased errors, but this trade-off may be worth it for labs with consistent and accurate formatting. 
Instead of extracting the `sample_is_private_column_name` and the `gisaid_id_column_name` columns, these columns are generated by the …
> CZGenEpi_Prep_PHB: implementing user-requested changes

- tasks/species_typing/task_pangolin.wdl
- tasks/species_typing/task_tbp_parser.wdl
- tasks/task_versioning.wdl
- tests/workflows/theiacov/test_wf_theiacov_clearlabs.yml
- tests/workflows/theiacov/test_wf_theiacov_fasta.yml
- tests/workflows/theiacov/test_wf_theiacov_ont.yml
- tests/workflows/theiaprok/test_wf_theiaprok_illumina_pe.yml
- tests/workflows/theiaprok/test_wf_theiaprok_illumina_se.yml
- workflows/utilities/wf_organism_parameters.wdl
> [PHB Release 1.3.0] update version and docker tags (nexclade sc2, pangolin, tbp-parser 1.1.7)

- workflows/phylogenetics/wf_nextclade_addToRefTree.wdl
This PR closes #<[302](https://github.com/theiagen/public_health_bioinformatics/issues/302)>.
This change is to avoid confusion between Theiagen's `organism` input for the various workflows and what was named as `organism` input in the `Samples_To_Ref_Tree_PHB` workflow, but is ideally the `nextclade_dataset_name`. For example, `flu` is accepted as `organism` input for the `TheiaCoV` workflows, but what is expected as the `organism` input in `Samples_To_Ref_Tree_PHB` is `flu_yam_ha`, or `flu_h1n1pdm_ha`, etc, depending on the subtype and segment.
Running this workflow on different occasions could …
> Samples_To_Ref_Tree_PHB: changed "organism" input to "nextclade_dataset_name"

- tasks/utilities/task_validate.wdl
- workflows/utilities/wf_theiavalidate.wdl
Closes (Issue moved to [theiagen/theiavalidate](https://github.com/theiagen/theiavalidate), issues [1](https://github.com/theiagen/theiavalidate/issues/1) and [2](https://github.com/theiagen/theiavalidate/issues/2])).
This pull request is associated with a [pull request](https://github.com/theiagen/theiavalidate/pull/5) in theiagen/theiavalidate to add file content comparisons to TheiaValidate. An array of diff files is added as an output to wf_theiavalidate.wdl. `docker` is also added as an input variable to task_validate.wdl to allow the user to select a different Docker image. The default image is still `"us-docker.pkg.dev/general-theiagen/theiagen/theiavalidate:0.0.1"`.
task_validate.wdl
wf_theiavalidate.wdl
A requested feature of TheiaValidate is the ability to compare file contents. …
> TheiaValidate: Compare file contents

- tasks/utilities/task_validate.wdl
- workflows/utilities/wf_theiavalidate.wdl
This PR closes the loop on the adding file comparisons to TheiaValidate
This PR pushes the changes into main that have been thoroughly tested as part of #264
TheiaValidate updated to now compare files
File comparison outputs now created
> TheiaValidate: Compare file contents (#264)

- tasks/taxon_id/task_freyja_one_sample.wdl
- workflows/freyja/wf_freyja_fastq.wdl
This PR closes #287 
This PR adds the Freyja coverage value to the Terra data table as a workflow output to provide more QC metrics to users.
This will affect the behavior of the workflow(s) even if users don’t change any workflow inputs relative to the last version : Yes New output will be provided as default
Running this workflow on different occasions could result in different results, e.g. due to use of a live database, "latest" docker image, or stochastic data processing : Not that I'm aware of- no changes made could lead to variable results
- New output, "freyja_coverage", containing coverage identified by Freyja and parsed from freyja_demixed.tsv file.
Data is not processed differently. Coverage is now parsed to the data …
> Added Freyja coverage output to Terra table

- .dockstore.yml
- tasks/assembly/task_semibin.wdl
- workflows/theiameta/wf_theiameta_illumina_pe.wdl
This PR closes #321
🗑️ This dev branch should be deleted after merging with main.
Binning is the next logical step when it comes to metagenomic analysis through assembly and genomic characterization. It allows us to (ideally) separate the components of a community into their contigs.
Two processes are needed for binning:
1. The clean reads need to be mapped to the metagenomic assembly to produce abundance information for each contig 
2. The contigs and the sorted and indexed bam files are used by the binning algorithm to produce (ideally) as many bins as there are individual species in a community. 
Downstream characterization is not yet done in this PR.
This will affect the behaviour of the workflow(s) even if users don’t change any workflow inputs relative to the last version : No …
> [TheiaMeta] Binning with SemiBin2

- .dockstore.yml
> fix dockstore: add empty.json file and update .dockstore.yml with absolute paths to it

- tasks/taxon_id/task_freyja_one_sample.wdl
- workflows/freyja/wf_freyja_fastq.wdl
This PR closes #147 
For a long time, we were simply outputting the name of the freyja barcodes file, but this proved to be useless since many of these are simply named "usher_barcodes.csv" and that turns out to not be useful when each "usher_barcodes.csv" file could be referencing a different one. Instead, we want to output the actual file used. That's what this PR does.
Running this workflow on different occasions could result in different results, e.g. due to use of a live database, "latest" docker image, or stochastic data processing : Yes, if `update_db` is set to true 
Docker/software or software …
> [Freyja_FASTQ] output usher_barcodes file to table

- tasks/taxon_id/task_kraken2.wdl
- tests/workflows/theiaprok/test_wf_theiaprok_illumina_pe.yml
- tests/workflows/theiaprok/test_wf_theiaprok_illumina_se.yml
This PR closes #224 
Most of our workflows in the PHB universe ™️ are meant to be compatible with both compressed and uncompressed FASTQ files. Such is the example of TheiaProk (https://theiagen.notion.site/TheiaProk-Workflow-Series-2c710e386ea74dbc828a910b6fb77fac)
> Read file names should end with .fastq or .fq, with the optional addition of .gz
Unfortunatly, this is no longer true since #286 as the addition of Kraken2 module made the workflow uncompatible with uncompressed files. 
TheiaMeta is another workflow that is also not currently compatible with uncompressed FASTQs due to Kraken2 standalone task incompatibility. 
This PR addresses this issue by allowing uncompressed FASTQ files to be processed by Kraken2. 
Additionally, …
> [Kraken2_Standalone] Make task compatible with uncompressed FASTQ files

- tasks/utilities/data_import/task_sra_fetch.wdl
Quick bugfix for a bug introduced in PR #310 
This PR closes #362 
Not planning to fill all of this ⬇️ out, it's a very simple PR. I'll run 1 test on Terra just to be sure
🗑️ This dev branch should  be deleted after merging to main.
> bug fix on fastq-dl task/SRA_fetch workflow for cpu variable

- tasks/assembly/task_irma.wdl
- workflows/theiacov/wf_theiacov_illumina_pe.wdl
This PR closes #361.
This PR fixes an issue with empty mean coverage estimates for influenza HA and Na assemblies.
This will affect the behavior of the workflow(s) even if users don’t change any workflow inputs relative to the last version : Yes
Running this workflow on different occasions could result in different results, e.g. due to use of a live database, "latest" docker image, or stochastic data processing : Yes, but not due to this change
Docker/software or software versions changed: No
Databases or database versions changed: No
Data processing/commands changed: Yes, to correctly capture BAM files used to calculate assembly coverage
File processing changed: No
Compute resources changed: No
No changes
No changes
Tested …
> Fix Empty Mean Coverage for Flu HA and NA Assemblies

- tasks/quality_control/advanced_metrics/task_vadr.wdl
- tasks/quality_control/basic_statistics/task_quast.wdl
- tasks/quality_control/read_filtering/task_fastp.wdl
- tasks/quality_control/read_filtering/task_trimmomatic.wdl
- tasks/utilities/submission/task_mercury_file_wrangling.wdl
- tests/workflows/theiaprok/test_wf_theiaprok_illumina_pe.yml
- tests/workflows/theiaprok/test_wf_theiaprok_illumina_se.yml
- workflows/freyja/wf_freyja_fastq.wdl
- workflows/theiacov/wf_theiacov_fasta.wdl
- workflows/theiacov/wf_theiacov_illumina_pe.wdl
- workflows/theiacov/wf_theiacov_illumina_se.wdl
- workflows/theiacov/wf_theiacov_ont.wdl
- workflows/theiaeuk/wf_theiaeuk_illumina_pe.wdl
- workflows/theiameta/wf_theiameta_illumina_pe.wdl
- workflows/theiaprok/wf_theiaprok_illumina_pe.wdl
- workflows/theiaprok/wf_theiaprok_illumina_se.wdl
- workflows/utilities/wf_organism_parameters.wdl
- workflows/utilities/wf_read_QC_trim_pe.wdl
- workflows/utilities/wf_read_QC_trim_se.wdl
This PR closes #365 and closes #366 and closes #367 and closes #368.
This PR aims to harmonize a few inputs in workflows and sub-workflows to better adhere to our style-guide!
This will affect the behavior of the workflow(s) even if users don’t change any workflow inputs relative to the last version : No, it changes only input parameters. Default JSON inputs will need to be updated
Please see `Files changed` for an exhaustive list of all the inputs that were adjusted!
Docker/software or software versions changed: None
Databases or database versions …
> [Style Guide] Semantic adjustments throughout the PHB universe

- .dockstore.yml
This PR fixes the dockstore.yml file for the Find_Shared_Variants workflow, that's it.
> Fix dockstore yml for Find Shared Variants wf

- tasks/taxon_id/task_nextclade.wdl
- tests/workflows/theiacov/test_wf_theiacov_clearlabs.yml
- tests/workflows/theiacov/test_wf_theiacov_fasta.yml
- tests/workflows/theiacov/test_wf_theiacov_ont.yml
- workflows/theiacov/wf_theiacov_clearlabs.wdl
- workflows/theiacov/wf_theiacov_fasta.wdl
- workflows/theiacov/wf_theiacov_fasta_batch.wdl
- workflows/theiacov/wf_theiacov_illumina_pe.wdl
- workflows/theiacov/wf_theiacov_illumina_se.wdl
- workflows/theiacov/wf_theiacov_ont.wdl
This PR closes #392 
Tamiflu resistance is now detected in its own special task, and so we  don't really want to have that duplicated! This PR removes the duplicate and now obsolete outputs. 
Just removes a few outputs and inputs that are now unnecessary.
Compute resources …
> [Nextclade & TheiaCoV] remove tamiflu amino acid substitution detection since duplicated

- tasks/utilities/submission/task_mercury_file_wrangling.wdl
This PR closes #396 
I personally haven't tested this but I am trusting in pandas
Adds state to the country column in accordance with new NCBI style
Added state to country if state is provided
> [Mercury_Prep_N_Batch] add state to country

- tests/workflows/theiaprok/test_wf_theiaprok_illumina_pe.yml
- tests/workflows/theiaprok/test_wf_theiaprok_illumina_se.yml
This PR closes #410.
This PR just fixes the CI in preparation for v2.0.0 release!
> [PHB v2.0.0] update CI

- tasks/species_typing/mycobacterium/task_tbprofiler.wdl
- tests/workflows/theiaprok/test_wf_theiaprok_illumina_pe.yml
- tests/workflows/theiaprok/test_wf_theiaprok_illumina_se.yml
- workflows/theiacov/wf_theiacov_illumina_pe.wdl
Also changed the name of the `docker` input param for the tbprofiler WDL task.
> theiacov_illumina_pe kraken output name change

- workflows/theiaeuk/wf_theiaeuk_illumina_pe.wdl
> [TheiaEuk] revert busco container to busco:v5.3.2_cv1 for theiaeuk

- tasks/task_versioning.wdl
- tests/workflows/theiaprok/test_wf_theiaprok_illumina_pe.yml
- tests/workflows/theiaprok/test_wf_theiaprok_illumina_se.yml
> Update version to v2.0.1

- workflows/utilities/wf_read_QC_trim_ont.wdl
This PR partially closes #301 
This PR adds a simple fix to kmc over-estimating the genome lengths on ONT data. This tends to happen when the FASTQs are extremely large (over 2GB in size).
To address this a simple catch has been implemented to prevent the estimated genome length to exceed 10M bases (as per #301 direction). 
This will affect the behavior of the workflow(s) even if users don’t change any workflow inputs relative to the last version : Yes, kmc genome size is not limited to a maximum of 10M bases
Docker/software or software versions …
> [TheiaProk_ONT] add patch fix to kmc estimated genome size to not go over 10Mbp

- tasks/quality_control/comparisons/task_screen.wdl
- tests/workflows/theiacov/test_wf_theiacov_illumina_pe.yml
- tests/workflows/theiacov/test_wf_theiacov_illumina_se.yml
- tests/workflows/theiacov/test_wf_theiacov_ont.yml
- tests/workflows/theiaprok/test_wf_theiaprok_illumina_pe.yml
- tests/workflows/theiaprok/test_wf_theiaprok_illumina_se.yml
- workflows/theiacov/wf_theiacov_ont.wdl
This PR closes #426 and closes #397 
This PR does two things: 
- adds assembly_mean_coverage for the HA & NA segments to ~~TheiaProk_ONT~~ TheiaCoV_ONT
- removes the organism-specific portions in the two read screen tasks as they are no longer being used ever and are leftovers that need to be thrown out like a moldy sandwich that was left to languish in the back of the fridge until someone finds it and realizes that it is less of a sandwich and more of a colony with family, friends, lovers, with children that play in the slices of ham and teens that sneak through the holes in the swiss cheese.  …
> [Flu] Assembly mean coverage & read screen clean-up

- tasks/utilities/submission/task_submission.wdl
This PR closes #435 
`skip_biosample` should avoid checking for biosample metadata, but it was not. :( Tragic. Anyways, now it skips that check so you don't need to provide it anymore.
`biosample_type` is now an optional variable
Checking for biosample metadata is skipped if you skip biosample …
> [Terra_2_NCBI] remove metadata requirements with skip_biosample == true

- workflows/utilities/wf_organism_parameters.wdl
This PR closes #500.
Sometimes you want to run TheiaCoV on an organism it doesn't natively support yet. This PR lets you do that.
If a standardized organism name is not found, the user-provided organism will be used instead, which will likely cause any organism-specific steps in the workflow to be skipped as the provided name is not recognized.
Tested [here](https://app.terra.bio/#workspaces/cdph-terrabio-taborda-manual/CDPH_Smith_ …
> [TheiaCoV] Enable user to run TheiaCoV with an unsupported organism

- tasks/gene_typing/drug_resistance/task_amrfinderplus.wdl
- tests/workflows/theiaprok/test_wf_theiaprok_illumina_pe.yml
- tests/workflows/theiaprok/test_wf_theiaprok_illumina_se.yml
- workflows/theiaprok/wf_theiaprok_fasta.wdl
- workflows/theiaprok/wf_theiaprok_illumina_pe.wdl
- workflows/theiaprok/wf_theiaprok_illumina_se.wdl
- workflows/theiaprok/wf_theiaprok_ont.wdl
This PR closes #504.
User requested having the Beta-Lactam AMR genes separated out by all beta-lactam and the respective beta-lactam subclasses.
All TheiaProk workflows now have the option to have the beta-lactam genes parsed out into individual columns and by subclass too.
Beta-Lactam is now parsed into its own columns
- `Boolean separate_betalactam_genes` 
- `String amrfinderplus_amr_betalactam_genes`
- `String amrfinderplus_amr_betalactam_betalactam_genes`
- `String amrfinderplus_amr_betalactam_carbapenem_genes`
- `String amrfinderplus_amr_betalactam_cephalosporin_genes`
- `String amrfinderplus_amr_betalactam_cephalothin_genes`
- `String amrfinderplus_amr_betalactam_methicillin_genes` …
> [AMRFinderPlus] parse BETA-LACTAM genes and subclasses into individual output columns

- workflows/theiaprok/wf_theiaprok_fasta.wdl
- workflows/theiaprok/wf_theiaprok_ont.wdl
This PR closes #285 
In the TheiaProk_ONT and TheiaProk_FASTA workflow, the hicap task is launched for _Haemophilus influenzae_ samples but the outputs are not currently included in the workflow outputs. This PR fixes this. 
- TheiaProk_FASTA
- New outputs added to the main workflow and export_taxon table
- TheiaProk_ONT
- New outputs added to the main workflow and export_taxon table
Docker/software or software versions …
> [TheiaProk] expose hicap outputs in theiaprok_fasta and theiaprok_ont

- tests/workflows/theiacov/test_wf_theiacov_clearlabs.yml
- tests/workflows/theiacov/test_wf_theiacov_fasta.yml
- tests/workflows/theiacov/test_wf_theiacov_illumina_pe.yml
- tests/workflows/theiacov/test_wf_theiacov_illumina_se.yml
- tests/workflows/theiacov/test_wf_theiacov_ont.yml
- workflows/theiacov/wf_theiacov_fasta_batch.wdl
- workflows/utilities/wf_organism_parameters.wdl
This PR closes #454 
To update the default docker image for pangolin
& to update the default nextclade dataset tags to the latest available at the current time
Changes were made to the `organism_parameters.wdl` subworkflow
- Impacts all TheiaCoV workflows that call Pangolin or Nextclade on SC2, Mpox, and Influenza
- Theiacov_fasta_batch
- Pangolin_Update
- (indirectly) Augur since it imports the organism_parameters subwf …
> update default pangolin docker (pdata 1.27) & nextclade dataset tags for SC2, Flu, Mpox

- tasks/task_versioning.wdl
- tests/workflows/theiaprok/test_wf_theiaprok_illumina_pe.yml
- tests/workflows/theiaprok/test_wf_theiaprok_illumina_se.yml
This PR closes #513 
upgrade the PHB version to 2.1.0 ahead of the release
Docker/software or software versions changed: `task_versioning.wdl` upgraded to output `PHB v2.1.0`
Databases or database versions changed: **N/A**
Data processing/commands changed: **N/A**
File processing changed: **N/A**
Compute resources changed: **N/A**
**N/A**
All PHB workflows will now output `PHB v2.1.0`
Doesn't matter, just need to test on …
> [all workflows] upgrade PHB version to 2.1.0

- .dockstore.yml
- tasks/utilities/data_import/task_create_terra_table.wdl
- workflows/utilities/data_import/wf_create_terra_table.wdl
This PR closes #259.
Users have reported the creation of the data tables the most difficult part of uploading data. This workflow eases that process by having the user provide the location of the data and indications on the data type, whether it is paired-end, single-end, or assembly data.
**DOES NOT WORK WITH DATA IN REQUESTER-PAYS BUCKETS**
This is a new workflow with a new task.
No changes to any existing workflows or tasks.
| Variable | Description | Type |
| --- | --- | --- |
| `Boolean assembly_data` | Use to indicate data consists of assembly fastas | Required |
| `String data_location_path` | The full path to the location (assumes Google) | Required |
| `String new_table_name` | The name of the table to be created | …
> Adding the Create_Terra_Table_PHB workflow

- tasks/quality_control/advanced_metrics/task_mummer_ani.wdl
- tests/workflows/theiaprok/test_wf_theiaprok_illumina_pe.yml
- tests/workflows/theiaprok/test_wf_theiaprok_illumina_se.yml
This PR closes #529 
When two top hits have the exact same score, TheiaProk fails and that is sad.
All TheiaProk workflows that run mummer-ani. 
This PR adds a `uniq` pipe to only include one of the two top hits.
Local tests on the particular sample that caused the failure succeeded.
Test on regular samples to ensure no unintended consequences.
> [TheiaProk - ANI] prevent failures when multiple top hits have the same score

- workflows/theiacov/wf_theiacov_illumina_pe.wdl
- workflows/theiacov/wf_theiacov_ont.wdl
- workflows/utilities/wf_flu_track.wdl
This PR closes #271.
Workflows fail sometimes due to user error or to poor quality data that is unable to be analyzed. This PR will prevent failures due to the inability to produce an assembly, which allows users to see the QC data that was calculated.
- Organism-specific tasks are encased in `if (defined(assembly_fasta))` blocks. 
- If an assembly cannot be produced, the output column will now say "Assembly could not be generated"
- This above part is subject to change
TheiaCoV_Illumina_PE: [here](https://app.terra.bio/#workspaces/cdph-terrabio-taborda-manual/ …
> [TheiaCoV] Flu: Prevent workflow failures when assembly cannot be produced; generate NanoPlot outputs regardless of assembly success

- tasks/species_typing/orthomyxoviridae/task_genoflu.wdl
- workflows/theiacov/wf_theiacov_fasta.wdl
- workflows/theiacov/wf_theiacov_illumina_pe.wdl
- workflows/theiacov/wf_theiacov_ont.wdl
- workflows/utilities/wf_flu_track.wdl
This PR closes #537.
This PR adds GenoFLU, a tool made by USDA, which will determine the whole-genome genotype of the sample
New task added GenoFLU to the flu_track
GenoFLU v1.03 added
New (appear in terra under `flu_track`):
- `File? …
> [TheiaCoV] Add GenoFLU for flu whole-genome genotyping

- tasks/quality_control/read_filtering/task_ncbi_scrub.wdl
This PR closes #551
A nasty little bug was found where the `awk` command was suppressing all reads from being written to the interleaved file. This bug was introduced in #527.
This has now been fixed! Yey!
A few more debug messages were added to ease debugging of the task!
Docker/software or software versions changed: None
Databases or database versions changed: None
Data processing/commands changed: Removed intermediary …
> [TheiaCoV and TheiaMeta - HRRT] Patch bug by removing unneeded awk verification

- tasks/quality_control/read_filtering/task_ncbi_scrub.wdl
…rification (#550)
* remove awk verification
* DEBUG is not ERROR
> [Freyja] Update to main

- .github/ISSUE_TEMPLATE/bug-report.md
- .github/ISSUE_TEMPLATE/feature-request.md
- .github/PULL_REQUEST_TEMPLATE.md
- README.md
- tasks/quality_control/read_filtering/task_ncbi_scrub.wdl
> Updating templates & broken links in the readme

- tasks/species_typing/mycobacterium/task_tbp_parser.wdl
- tasks/task_versioning.wdl
- tests/workflows/theiaprok/test_wf_theiaprok_illumina_pe.yml
- tests/workflows/theiaprok/test_wf_theiaprok_illumina_se.yml
- workflows/utilities/wf_merlin_magic.wdl
🗑️ This dev branch should **NOT** be deleted after merging to main.
- merge conflict is due to versioning task. will need to undo before merge to main and then readd after merging
- updates tbp-parser to 1.6.0 and exposes optional inputs
- additional optional inputs
- updated docker
- 
This branch has been extensively tested & validated by CDPH and other laboratories.  No additional testing needed.
> [TheiaProk] update tbp-parser to latest version

- tasks/utilities/data_import/task_create_terra_table.wdl
- workflows/utilities/data_import/wf_create_terra_table.wdl
This PR closes #566.
- Enable user-provided file endings to determine what to drop from the file's basename to determine samplename
- Fix a bug where the `grep` was doing some weird things 
This PR may lead to different results in pre-existing outputs: **Yes** because a bug is being fixed
- enable a regex-compatible  optional input that can be comma-delimited to truncate filenames as desired by the user
- fix a bug
None
None
see [here](https://app.terra.bio/#workspaces/theiagen-validations/sage/job_history/4629bde8-539f-46a5-beee-c2fb899b1748)
> [Create_Terra_Table] fix bug, and enable ability for users to provide their own file ending suffixes

- tasks/species_typing/multi/task_ts_mlst.wdl
- tests/workflows/theiaprok/test_wf_theiaprok_illumina_pe.yml
- tests/workflows/theiaprok/test_wf_theiaprok_illumina_se.yml
This PR closes #583 
This PR updates the mlst docker image from 2.23.0-2024-06-01 to 2.23.0-2024-08-01
`task_ts_mlst.wdl`
Selected E. coli and V. cholerae samples fromt he validation dataset to perform functional tests. The docker image updates should have the workflows run as before.
TheiaProk_Illumina_PE_PHB
https://app.terra.bio/#workspaces/theiagen-training-workspaces/Theiagen_Otieno_Sandbox/job_history/4437b466-ff06-408a-80ec-11555d2710f7
TheiaProk_Illumina_SE_PHB
https://app.terra.bio/#workspaces/theiagen-training-workspaces/Theiagen_Otieno_Sandbox/job_history/ …
> Updating mlst docker image to 2.23.0-2024-08-01

- tasks/task_versioning.wdl
- tests/workflows/theiaprok/test_wf_theiaprok_illumina_pe.yml
- tests/workflows/theiaprok/test_wf_theiaprok_illumina_se.yml
This PR closes #584 
upgrade the PHB version to 2.2.0 ahead of the release
`task_versioning.wdl` upgraded to output `PHB v2.2.0`
All PHB workflows will now output PHB v2.2.0
Two V cholerae samples taken through TheiaProk_Illumina_PE_PHB
https://app.terra.bio/#workspaces/theiagen-training-workspaces/Theiagen_Otieno_Sandbox/job_history/a38e1304-f7ef-43ef-a60e-fed6f5b3b584
version output is updated as expected
Any dataset and any workflow
> Upgrade PHB to version 2.2.0

- tasks/utilities/submission/task_mercury.wdl
This PR fixes a bug when trying to skip NCBI submission.
> [Mercury] Resolve bug when skipping NCBI submission

- docs/workflows/phylogenetic_construction/snippy_variants.md
This PR updates the documentation related to Snippy variants output. Specifically, it adds clear descriptions of the coverage-related output variables (snippy_variants_coverage_tsv and snippy_variants_percent_ref_coverage), highlighting the differences between the two:
snippy_variants_coverage_tsv: Coverage statistics TSV file generated by the samtools coverage command, providing genome-wide metrics such as the proportion of bases covered (depth ≥ 1), mean depth, and other related statistics.
snippy_variants_percent_ref_coverage: Proportion of the reference genome covered by reads with a depth greater than or equal to the min_coverage threshold (default is 10).
This distinction clarifies how each coverage output …
> [Documentation] Updated Snippy variants output documentation

- docs/workflows/genomic_characterization/theiacov.md
This PR closes #651 
Fixes documentation for theiacov, line 962, changing that assembly for irma is assembled from largest to smallest NOT smallest to largest. 
Line 962 on theiacov docs fixed.
> Fixed theiacov documentation to specify assembly order

- README.md
- docs/contributing/doc_contribution.md
- docs/index.md
- docs/workflows/genomic_characterization/pangolin_update.md
- docs/workflows/genomic_characterization/theiacov.md
- docs/workflows/genomic_characterization/theiameta.md
🗑️ This dev branch should  be deleted after merging to main.
Just docs
-  The workflow/task has been tested and results, including file contents, are as anticipated
-  The CI/CD has been adjusted and tests are passing (Theiagen developers)
-  Code changes follow the [style guide](https://theiagen.notion.site/Style-Guide-WDL-Workflow-Development-51b66a47dde54c798f35d673fff80249)
- All changed results have been confirmed
-  You have tested the PR appropriately (see the [testing guide](https://theiagen.notion.site/PR-Testing-Guide-Determining-Appropriate-Levels-of-Testing-4764e98a6aeb460185039c0896714590) for more information)
- MD5 sums have been updated
> [Documentation] Various updates

- docs/workflows/genomic_characterization/theiacov.md
Updates dataset tags for Nextclade
Updates organism specific theiacov docs for nextclade
Updated organism-specific docs
> [Documentation] update dataset tags

- docs/stylesheets/extra.css
- docs/workflows/phylogenetic_construction/augur.md
This PR closes #705 
sets the table max width to be the size of the viewport
sets the table data cell element to overflow-wrap: anywhere so that overflow doesn't happen
none
- [NA] You have updated the latest version for any affected worklows in the respective workflow documentation page and for every entry in the three `workflows_overview` tables.
> [Documentation] Fix overflow in Augur documentation

- docs/workflows/genomic_characterization/theiacov.md
- tasks/species_typing/orthomyxoviridae/task_genoflu.wdl
This PR closes #703 
- updates GenoFLU docker to v1.05
- TheiaCoV workflows with the flu track (FASTA, ONT, PE)
- updated genoflu docker could lead to different detected genotypes
- docker 1.03 -> 1.05
None
None
- [TheiaCoV_ONT](https://app.terra.bio/#workspaces/cdph-terrabio-taborda-manual/CDPH_Bioinformatics_Development/job_history/8862e93e-31aa-4c67-a172-95a1c2657e83)
- [TheiaCoV_Illumina_PE](https://app.terra.bio/#workspaces/cdph-terrabio-taborda-manual/CDPH_Bioinformatics_Development/job_history/952976d5-c4ce-4dc1-b44b-2ab79a0496d9)
- …
> [GenoFLU] update docker to v1.05

- docs/assets/files/TheiaCoV_Illumina_PE_qc_check_template.tsv
- docs/workflows/genomic_characterization/theiacov.md
- docs/workflows/genomic_characterization/theiaeuk.md
- docs/workflows/genomic_characterization/theiaprok.md
This PR closes #572 
This PR adds the qc_check part to the TheiaCoV docs. Looks like this had been done but after I transferred everything over, so I copied it into our stuff.
> [Documentation] add qc check documentation to TheiaCoV 

- docs/contributing/code_contribution.md
- docs/getting_started/philosophy.md
- mkdocs.yml
This PR closes nothing but the gaping hole in my heart.
Adding a page that describes our philosophy regarding how our workflows should function regardless of data quality.
> [Documentation] Adding philosophy of workflow failures page

- docs/workflows/data_import/sra_fetch.md
- workflows/utilities/data_import/wf_sra_fetch.wdl
This PR closes #451
Adds PHB version query and outputs version and analysis date
wf_sra_fetch.wdl
Import call_versioning task, call, and output version and analysis date into table
Import `task_versioning.wdl` from PHB tasks
No new inputs
PHB version is now included within sra_fetch output via call-version_capture
`String sra_fetch_version = version_capture.phb_version`
`String sra_fetch_analysis_date = version_capture.date`
miniwdl run of SRR11435983 retrieval 
Terra run using [30 bacterial SRAs](https://app.terra.bio/#workspaces/theiagen-training-workspaces/Theiagen_Konke …
> [SRA-Fetch] query and report PHB version

- tasks/quality_control/comparisons/task_screen.wdl
- tests/workflows/theiacov/test_wf_theiacov_illumina_se.yml
- tests/workflows/theiacov/test_wf_theiacov_ont.yml
- tests/workflows/theiaprok/test_wf_theiaprok_illumina_pe.yml
- tests/workflows/theiaprok/test_wf_theiaprok_illumina_se.yml
Emergency change address failure due to invalid variable call
Fix bash to wdl variable reference
n/a
n/a
Tested failure state in [SE:](https://app.terra.bio/#workspaces/theiagen-training-workspaces/Theiagen_Konkel_Sandbox/job_history/672015de-87c1-4fc7-849f-ce9e8b8f6921) resolved
> [Read_Screen] BUG fix $ to ~ reference for workflow series

- docs/assets/new_workflow_template.md
- docs/contributing/doc_contribution.md
This PR closes nothing but an internal need for order
- clarifies the new workflow documentation template
none 
- please serve documentation locally to confirm working appropriately
> [Documentation] improve new workflow template

- docs/workflows/genomic_characterization/theiacov.md
- docs/workflows/phylogenetic_placement/samples_to_ref_tree.md
- tasks/taxon_id/task_nextclade.wdl
- tests/workflows/theiacov/test_wf_theiacov_clearlabs.yml
- tests/workflows/theiacov/test_wf_theiacov_fasta.yml
- tests/workflows/theiacov/test_wf_theiacov_illumina_pe.yml
- tests/workflows/theiacov/test_wf_theiacov_illumina_se.yml
- tests/workflows/theiacov/test_wf_theiacov_ont.yml
- workflows/utilities/wf_organism_parameters.wdl
Updates the nextclade version from 3.31 to 3.10.2 and updates the nextclade dataset tags to the latest tags available. 
Workflow series:
`TheiaCoV Series`
- Just impacted downstream in general since nextclade tags updated in wf_organism_parameters.wdl
Workflows:
`wf_organism_parameters` - tags updated for latest ones corresponding to organisms
Tasks:
`nextclade_v3`
`nextclade_add_ref`
Updated version from 3.3.1 to 3.10.2
The following tags have been updated to the latest in wf_organism_parameters
| Dataset Name | Latest Tag | Previous Tag | …
> [Nextclade] Update nextclade software version and dataset tags to latest

- docs/workflows/genomic_characterization/freyja.md
- tasks/taxon_id/freyja/task_freyja.wdl
- tasks/taxon_id/freyja/task_freyja_dashboard.wdl
- tasks/taxon_id/freyja/task_freyja_plot.wdl
- tasks/taxon_id/freyja/task_freyja_transfer.wdl
- tasks/taxon_id/freyja/task_freyja_update.wdl
- workflows/freyja/wf_freyja_fastq.wdl
> [Freyja] Add pathogen flag to all commands

- tasks/species_typing/vibrio/task_vibecheck_vibrio.wdl
- tests/workflows/theiaprok/test_wf_theiaprok_illumina_pe.yml
- tests/workflows/theiaprok/test_wf_theiaprok_illumina_se.yml
- workflows/utilities/wf_merlin_magic.wdl
[testing here](https://app.terra.bio/#workspaces/theiagen-validations/PHB_Validation_v3-0-0/submission_history/46086bb7-9897-4f59-ab39-c57f1b3fd806)
> [TheiaProk] prevent Vibecheck from running on SE data

- docs/workflows/standalone/amr_search.md
- docs/workflows/standalone/theiavalidate.md
- tasks/utilities/data_handling/task_validate.wdl
> [TheiaValidate] update docker to v1.1.2

- docs/workflows/genomic_characterization/theiaprok.md
- tasks/species_typing/multi/task_ts_mlst.wdl
- tests/workflows/theiaprok/test_wf_theiaprok_illumina_pe.yml
- tests/workflows/theiaprok/test_wf_theiaprok_illumina_se.yml
This PR closes # 714
Update Docker containers to rectify incorrect typing assignment
task_ts_mlst.wdl
Update docker container to 2024-12-31
n/a
n/a
n/a
n/a
> [MLST] update docker container

- docs/contributing/doc_contribution.md
- docs/workflows/genomic_characterization/freyja.md
This PR clarifies some language for running Freyja on non-SC2 organisms. 
None; this only changes documentation. 
No.
No. 
1) Changes to the description of how to run non-SC2 pathogens to make it clearer that one can either supply a pathogen flag + update_db == true OR supply a barcode file. And that a lineage metadata file is not necessary for a non-SC2 pathogen sample.
2) I removed H3N2 from the list of pathogens you can supply a pathogen flag for. (H3N2 samples can be run when a barcode file is supplied.)
3) Added quotes to strings in the …
> [Documentation] Update Freyja documentation page

- docs/assets/tables/all_outputs.tsv
- docs/common_text/kmerfinder_task.md
- docs/workflows/genomic_characterization/theiaeuk.md
- docs/workflows/genomic_characterization/theiaprok.md
This PR closes #815 and #829 
Update docs of TheiaEuk to better reflect `genome_length` input as well as include more information in the description of KmerFinder. Web addresses have also been turned into links for ease of access. Also applying new documentation format. 
Documentation updates. 
NA
NA
NA
Utilized `mkdocs serve` to check links and formatting.
> [KmerFinder, TheiaEuk] Docs update to include links and more in depth description

- tasks/species_typing/mycobacterium/task_tbp_parser.wdl
This PR fixes the percent coverage and average depth calculations for tNGS data in tbp_parser.
- `task_tbp_parser.wdl`
- `wf_tbprofiler_tngs.wdl`
`tbp_parser` can operate with both WGS and tNGS data. In the `task_tbp_parser.wdl` task, there's an output that calculates the genome percent coverage for the entire reference genome and an output that calculates the average depth of coverage. Both of these calculations made assumptions that the input alignment file represented whole genome sequencing data. However, these calculations do not apply …
> [tbp_parser] Fixing percent coverage calculation for tNGS analysis

- tasks/gene_typing/drug_resistance/task_amrfinderplus.wdl
- tests/workflows/theiaprok/test_wf_theiaprok_illumina_pe.yml
- tests/workflows/theiaprok/test_wf_theiaprok_illumina_se.yml
This PR closes #901 
This PR updates the database version of AMRFinderPlus to 2025-07-16.1.
Changes to database detailed [here](https://ftp.ncbi.nlm.nih.gov/pathogen/Antimicrobial_resistance/AMRFinderPlus/database/latest/changes.txt). 
Highlights being:
```
Updates since release 2025-06-03.1:
Proteins added: 73
Core proteins added: 72
Plus proteins added: 1
AMR proteins added: 73
Alleles added: 61
PubMed references added: 59
Point mutations added: 43
Added organism options: Bordetella_pertussis
Reference Gene Catalog entries changed: 282
Hierarchy nodes added: 19
Hierarchy nodes removed: 1
Hierarchy nodes changed: 6
```
TheiaProk Suite
NCBI_AMRFinderPlus_PHB …
> [AMRFinderPlus] Update to database version 2025-07-16.1
