tasks/taxon_id/task_gambit.wdl
workflows/wf_merlin_magic_euk.wdl
workflows/wf_theiaeuk_pe.wdl

This PR does the following:
- adds support for Cryptococcus neoformans
- adds complete list of genes containing known resistance conferring mutations for all organism-specific antifungal resistance detection modules
- modifies default screening parameters based on known max and min sizes of pathogenic fungal genomes

Fja antifungal dev

---

workflows/wf_merlin_magic_euk.wdl

This PR addresses an issue in which samples where the gambit_predicted_taxon results in a merlin_tag of "None" fail the wf_merlin_magic_euk.wdl workflow. This can occur when gambit fails to predict a taxon or when the predicted taxon does not match a merlin_tag. This issue is described in issue https://github.com/theiagen/public_health_bioinformatics/issues/16. 
The failure occurs because several of the merlin_magic_euk outputs are files produced by the snippy variants task, and select_first is used to select the correct output file for the sample's taxon. Currently, when merlin_tag == "None", the merlin magic euk workflow creates an empty string variable called "snippy_variant_none" that it attempts to use for these outputs. However, a string cannot be coerced to a file, causing the …

Fix merlin_magic_euk when merlin_tag is "None"

---

tasks/quality_control/task_nanoplot.wdl
tasks/quality_control/task_nanoq.wdl
tasks/quality_control/task_screen.wdl
workflows/utilities/wf_read_QC_trim_ont.wdl

This introduces a task file that will produce an html file containing plots summarizing basic statistics of the nanopore raw reads.

add nanoplot to wf_read_QC_trim_ont.wdl

---

tasks/assembly/task_shovill.wdl
tasks/quality_control/task_cg_pipeline.wdl
tasks/quality_control/task_quast.wdl
tasks/species_typing/task_cauris_cladetyper.wdl
tasks/taxon_id/task_gambit.wdl
workflows/theiaeuk/wf_theiaeuk_illumina_pe.wdl
workflows/utilities/wf_merlin_magic.wdl

- Exposes runtime parameters for the the TheiaEuk, Nullarbor and MycoSNP workflows to allow apples-to-apples comparison
- Updates fungal GAMBIT database files to v0.2 and updates the file locations to the rp bucket
- Adds the product name for ERG11 to the resistance gene query because the "ERG11" gene name is not found in all reference genome files for Candida auris
- Additionally updates have been made to the reference files used in the C. auris cladetyper task and the subsequent snippy task. 
The reference files are available here:
ref_clade1_annotated = "gs://theiagen-public-files/terra/candida_auris_refs/Cauris_Clade1_GCA_002759435_Cauris_B8441_V2_genomic.gbff"
ref_clade2_annotated = "gs://theiagen-public-files/terra/candida_auris_refs/Cauris_Clade2_GCA_003013715.2_ASM301371v2_genomic. …

Correct C. auris reference files

---

tasks/assembly/task_shovill.wdl
workflows/theiacov/wf_theiacov_illumina_pe.wdl
workflows/theiacov/wf_theiacov_illumina_se.wdl
workflows/theiaeuk/wf_theiaeuk_illumina_pe.wdl
workflows/theiaprok/wf_theiaprok_illumina_pe.wdl
workflows/theiaprok/wf_theiaprok_illumina_se.wdl

This PR:
- Makes default trimming parameters inputs at the workflow level (TheiaCoV, TheiaProk, TheiaEuk) to fix issue where PHVG parameters were used for TheiaProk and TheiaEuk
- Lowers min_proportion read screen in TheiaEuk from 50 to 40
- Lowers min_basepairs read screen in TheiaEuk from 90000000 to 45000000 because it assesses the nucleotides in only one read file
- Modifies shovill_se task to use SKESA rather than SPAdes

Fix default trimming parameters 

---

workflows/phylogenetics/wf_snippy_tree.wdl

This PR adds the -c param to snp_sites in snippy_tree to obtain a true core genome alignment

Fix snp_sites in snippy_tree workflow

---

workflows/utilities/data_import/wf_basespace_fetch.wdl

Setting as a draft for now until further testing is completed in Terra with a variety datasets
The purpose of this PR is to account for when Illumina/Basespace/`bs` CLI tool converts underscores `_` in samples names to hyphens `-` in basepace-downloaded FASTQ files.
For example the sample name `133_121308_G_086`, contains underscores and thus the FASTQ files downloaded via basespace will be named like so, where all underscores in the sample name are converted to hyphens:
```
133-121308-G-086_S95_L001_R1_001.fastq.gz
133-121308-G-086_S95_L001_R2_001.fastq.gz
```
So this PR does the following:
- uses `sed` to take the sample name as entered by the user & specified in the Illumina `SampleSheet.csv` file 
- converts underscores into hyphens and stores that new sample name in the bash variable …

basespace_fetch_PHB: account for underscores in sample name

---

workflows/utilities/data_import/wf_sra_fetch.wdl

also exposed optional inputs for docker, disk_size, memory, cpus. 
tested fine with miniwdl and on Terra (but only in cases where data is available on ENA).
2 tests on Terra:
1. https://app.terra.bio/#workspaces/cdph-terrabio-taborda-manual/CDPH_PulseNet/job_history/c1e1c9a1-698a-4794-8fa5-2ba6af7c5ccd
2. The failures for this submission are due to data not being available on ENA, safe to ignore for now. https://app.terra.bio/#workspaces/cdph-terrabio-taborda-manual/CDPH_PulseNet/job_history/81e35181-03cd-4841-b0bf-4b498257f5fd
If data is not available on ENA, the workflow will fail, but this is a rare scenario where either the SRA accession is incorrect or the data was only recently (last1-2 weeks) uploaded to SRA (and thus not yet synced to ENA).
`fastq-dl` will soon be updated to query …

updated SRA_Fetch_PHB workflow to use fastq-dl v2.0.1

---

.dockstore.yml
tasks/utilities/submission/task_mercury_file_wrangling.wdl

This PR adds the "covv_consortium" column to the output GISAID metadata file. This new optional column has been added to the metadata formatter, which can be found [here](https://console.cloud.google.com/storage/browser/theiagen-public-files/terra/mercury-files?authuser=0&project=theiagen-public-resources&supportedpurview=project) at `gs://theiagen-public-files/terra/mercury-files/Mercury_Prep_N_Batch_SC2_Metadata_Formatter_2023_05_22.xlsx`.
I also added Terra_2_NCBI to the PHB dockstore file.

Add consortium to Mercury_Prep_N_Batch

---

.dockstore.yml
tasks/task_versioning.wdl
tests/workflows/theiaprok/test_wf_theiaprok_illumina_pe.yml
tests/workflows/theiaprok/test_wf_theiaprok_illumina_se.yml
workflows/utilities/wf_merlin_magic.wdl

Removing C.albicans subworkflow for now as current TheiaEuk workflow not designed for diploid assembly
Drops support for further characterization of a diploid organism.
`workflows/utilities/wf_merlin_magic.wdl` modified to:
- Comment out the C.albicans subworkflow to avoid use of `Snippy_Variants` on samples identified as C.albicans
- Adjust output block accordingly
Functional test on Terra using TheiaEuk validation table: https://app.terra.bio/#workspaces/theiagen-validations/Libui-Sandbox_2023/job_history/c497244c-93ce-41cf-b83b-1c6069c9a6e1

Removing C.albicans subworkflow

---

tasks/species_typing/task_srst2_vibrio.wdl
tests/workflows/theiaprok/test_wf_theiaprok_illumina_pe.yml
tests/workflows/theiaprok/test_wf_theiaprok_illumina_se.yml
workflows/utilities/wf_merlin_magic.wdl

Adds some logic flags to prevent assemblies & ont data from being run on Illumina-specific Vibrio task.
Also changed reads1 and reads2 to read1 and read2

Prevent assemblies & ONT data from Vibrio submodules

---

workflows/phylogenetics/wf_snippy_streamline.wdl

Closes #88 
`assembly_fasta` is a required input for Snippy_Streamline; however, if a reference is provided, `assembly_fasta` is not used but still considered required. I have changed assembly_fasta to be optional. 

make assembly_fasta optional

---

tasks/utilities/task_summarize_data.wdl

This PR adds several changes to the `summarize_data` task:
- the ability to specify a different column to use as samplenames
- prevents failures due to variable typing
- adds a new output that consists of the "filtered" metadata -- only the columns of interest
As per request
New optional input: `id_column_name` which should be filled with the name of the "samplename" column in the case where samplename is not the root entity column.
New output: the filtered metadata tsv
Local tests worked.
Test peformed here: https://app.terra.bio/#workspaces/theiagen-sphl-nevada/dataAnalysis_BACT_NV_PHL/job_history/84ee85ec-96fe-4200-91c2-f50e5ca63821

New metadata output on summarize_data task for phylogenetic workflows

---

.github/workflows/pytest-workflows.yml
tasks/species_typing/task_shigeifinder.wdl
tests/workflows/theiaprok/test_wf_theiaprok_illumina_pe.yml
tests/workflows/theiaprok/test_wf_theiaprok_illumina_se.yml

Closes #100
~~Set as a draft until the `staphb/shigeifinder:1.3.5` docker image is available ➡️  https://github.com/StaPH-B/docker-builds/pull/687~~ Docker image is now available 
- updated default docker to `staphb/shigeifinder:1.3.5`
- ⚠️ ~~This docker image is not yet available, but should be soon. Waiting for review over on StaPH-B/docker-builds before making this PR ready for review (and merging the PR of course).~~
- updated version capture line to use new option `shigeifinder --version`
- ⚠️ These changes will be incompatible with shigeifinder v1.3.4 and older. Users must use 1.3.5 or newer in order for this task to run successfully
- exposed memory as optional input String for both shigeifinder WDL tasks (asm input and reads input tasks)
Version capture for shigeifinder was …

shigeifinder 1.3.5 updates

---

.github/workflows/pytest-workflows.yml
tasks/utilities/task_validate.wdl
tests/config/pytest_filter.yml

Closes #92 and closes #94 
- casts table during exact match comparison to string
- prevents "NA" from being read as a NA value -- now is considered a string
These changes will improve accuracy.
No Change
No change
Local tests succeeded.
Test running here: https://app.terra.bio/#workspaces/theiagen-validations/PHB_Validation_v1-0-0/job_history/e39a7b82-2918-4ce2-8b0e-9a0b98a9368c

TheiaValidate fixes

---

workflows/utilities/data_import/wf_basespace_fetch.wdl

I added a brief `sed` statement to convert periods to dashes so that the downloaded read file can be identified. This is similar to  the previous issue we had in BaseSpace_Fetch with underscores turning into dashes.
Tests succeeded in the PR-SCITRUST workspace.

BaseSpace_Fetch: convert periods to dashes

---

.github/workflows/pytest-workflows.yml
tasks/phylogenetic_inference/task_lyveset.wdl
tasks/taxon_id/task_nextclade.wdl
tests/config/pytest_filter.yml
tests/workflows/theiacov/test_wf_theiacov_clearlabs.yml
tests/workflows/theiacov/test_wf_theiacov_fasta.yml
tests/workflows/theiacov/test_wf_theiacov_ont.yml

Updates to the Nextclade output parsing.
The latest Nextclade dataset tag (`2023-06-16T12:00:00Z`) removes the `clade_legacy` output column> Because of this, in order to maintain continuity with existing dashboards, we have decided to concatenate the `clade_nextstrain` and `clade_who` columns to mimic the content of the original `clade_legacy` output column. 
I also went through and adjusted formatting to match the style guide and removed unnecessary else statements.
https://app.terra.bio/#workspaces/cdc-terra-resources/Theiagen_Wright_SC2_Sandbox/job_history/2f4c5c0f-a9da-4c50-badf-acd2e46b7e8d

Update Nextclade Parsing

---

.github/workflows/pytest-workflows.yml
tests/workflows/theiacov/test_wf_theiacov_illumina_pe.yml
tests/workflows/theiacov/test_wf_theiacov_illumina_se.yml
workflows/utilities/wf_ivar_consensus.wdl

Due to a incompatibility error, we had previously removed the miniwdl tests for TheiaCoV_Illumina_PE and _SE. We've fixed the error, and since re-added the miniwdl test.s.
- ~The workflow/task has been tested locally and on Terra~

GHA for TheiaCoV_Illumina_PE/_SE

---

tasks/species_typing/task_shigatyper.wdl
tests/workflows/theiaprok/test_wf_theiaprok_illumina_pe.yml
tests/workflows/theiaprok/test_wf_theiaprok_illumina_se.yml
workflows/utilities/wf_merlin_magic.wdl

Opened a new PR so I don't pollute the commit history with my old PR and failed attempt at rebasing. 
Need to update CI and test once more in Terra, but should be ready for review shortly
- updated default shigatyper docker image to v2.0.5 (from 2.0.3) hosted on GAR
- added optional Integer input `memory` for shigatyper task. 
- exposed optional String input `shigatyper_docker_image` in merlin_magic subwf so that user has the ability to change via TheiaProk workflows in Terra
Previously the user was not able to adjust the shigatyper docker image, meaning they were stuck with the previous version that had a bug with Shigella flexneri serotyping. The updated version 2.0.5 fixes this bug. 
The usual TheiaProk workflow
only tested on Terra, these are minor changes
Successful workflow: …

small shigella updates, take 2

---

README.md
tasks/quality_control/task_busco.wdl
tests/workflows/theiaprok/test_wf_theiaprok_illumina_pe.yml
tests/workflows/theiaprok/test_wf_theiaprok_illumina_se.yml

This PR updates the default docker image for BUSCO to `us-docker.pkg.dev/general-theiagen/ezlabgva/busco:v5.3.2_cv1`. Must have missed that when we switched to all the GAR-hosted images.
I've double checked that the GAR docker image repo is public, as `allUsers` can read the artifact registry repo
This also exposes optional Int inputs `cpu` and `memory` in case it's ever necessary for the user
So that we are not relying upon an docker image & repo that we do not maintain or have control over.
NA
NA
NA
Did not test locally, this is a simple PR
Tested with TheiaProk_Illumina_PE_PHB here, ~~I expect it to run successfully~~ it ran successfully: https://app.terra.bio/#workspaces/theiagen-validations/curtis-sandbox-theiagen-validations/job_history/6427308f-7659-48d6-97db-932431df1610
Pull …

update default docker for busco to GAR docker image

---

tasks/phylogenetic_inference/task_mashtree.wdl
workflows/phylogenetics/wf_mashtree_fasta.wdl

~~Setting as draft until I test in Terra.~~ Just noticed that the user cannot alter the docker image used for mashtree and there is no `docker` output string.
- expose optional string input `docker` for mashtree task
- added new String output `docker` for mashtree task & `mashtree_docker` String output for the mashtree workflow
More flexibility
Did not test locally, this is a simple change
[Tested successfully in Terra](https://app.terra.bio/#workspaces/theiagen-validations/curtis-sandbox-theiagen-validations/job_history/41f361e5-6f05-46ed-8cf0-2f400ca2ee2b). Was able to pass in an optional docker input string, which was used correctly. Also produced the correct output string/column for `mashtree_docker`

minor mashtree improvements

---

tasks/utilities/task_summarize_data.wdl

- bugfix: Added double quotes around a WDL variable in the `tasks/utilities/task_summarize_data.wdl` that is an optional component of Mashtree_fasta_PHB workflow.
Prior to this change, if the optional `summarize_data` task was turned on by the user defined input of `data_summary_column_names` optional String AND if the user left the optional string input `id_column_name` blank/null, then the task would fail with an error like so:
```
/cromwell_root/script: line 37: unexpected argument `]]' to conditional unary operator
/cromwell_root/script: line 37: syntax error near `;'
/cromwell_root/script: line 37: `  if [[ -z  ]]; then'
```
When the double quotes are included in that line (see file changes), the bash conditional is evaluated to `true` (as the input was not given by the user), and it …

summarize_data task bug fix: -z bash conditional

---

tasks/assembly/task_dragonflye.wdl
tasks/quality_control/task_screen.wdl
tests/workflows/theiacov/test_wf_theiacov_illumina_pe.yml
tests/workflows/theiacov/test_wf_theiacov_illumina_se.yml
tests/workflows/theiacov/test_wf_theiacov_ont.yml
workflows/theiacov/wf_theiacov_illumina_se.wdl
workflows/theiacov/wf_theiacov_ont.wdl
workflows/theiaprok/wf_theiaprok_illumina_se.wdl
workflows/theiaprok/wf_theiaprok_ont.wdl

Closes #158 and #157 
- Outputs the GFA from Dragonflye
- Introduces new optional Boolean variable `skip_mash` which will skip the mash sketch genome size estimation in the read screen

Output Dragonflye GFA & modify read screen in TheiaProk_ONT

---

tasks/utilities/task_file_handling.wdl

I add a "skip_extra_headers" Boolean to the concatenate_column_content workflow that will skip any extra headers in the case of concatenating files with redundant headers.
New optional Boolean input that is defaulted to false: `skip_extra_headers`
Not locally tested.
Success: https://app.terra.bio/#workspaces/cdc-terra-resources/Theiagen_Wright_SC2_Sandbox/job_history/ff9994f6-2234-41b8-89a7-54b9a94ab365

Skip extra headers in Concatenate_Column_Content

---

tasks/species_typing/task_tbprofiler.wdl

All changes to task_tbprofiler.wdl, im-tbprofiler branch.
* Fixes the way TBProfiler's version is called 
* The regex might need further adjustment, since the output file reads `TBProfiler version \nTBProfiler version TBProfiler version 4.4.2`, but since I'm not sure what the intended output is I've left it
* Output median coverage
* Output percent unmapped
I've been tasked with CDPH to integrate this version of TBProfiler into a TB pipeline, along with CDC QC metrics. CDC QC metrics look for percent unmapped r/e whether or not a sample should be thrown out. Median coverage isn't one of those metrics, but it's a great way to catch low-coverage samples early on.
Unchanged.
Unchanged.
Adds:
* Int tbprofiler_median_coverage
* Integer representing what tbprofiler considers the median coverage …

TBProfiler: Fix minor bug; output median cov, % unmapped

---

tasks/species_typing/task_tbp_parser.wdl
tasks/species_typing/task_tbprofiler.wdl

* Default to running the two modified task on [preemptible instances](https://cloud.google.com/compute/docs/instances/preemptible), iff running on GCP
* Will only attempt preemptibles once, and if the task fails on the preemptible, it will try a non-preemptible.
* TBProfiler version string is now just the version as float, with no newlines
The preemptible runtime attribute makes running short-lived tasks significantly (~50-80%) cheaper on GCP, including Terra. [miniwdl](https://github.com/chanzuckerberg/miniwdl/blob/6052fa836ea0cd91c7a07a6a2766b6cf44c0afe0/WDL/Lint.py#L1072) and [Cromwell](https://cromwell.readthedocs.io/en/stable/RuntimeAttributes/#preemptible) will both ignore this runtime attribute if not running on a GCP backend, so this won't cause compatibility issues. …

Add preemptibles, shorter version string

---

workflows/phylogenetics/wf_snippy_tree.wdl

Closes[ #189](https://github.com/theiagen/public_health_bioinformatics/issues/189)
Added an optional `snippy_core_bed` file input to the [Snippy_Tree](https://github.com/theiagen/public_health_bioinformatics/blob/main/workflows/phylogenetics/wf_snippy_tree.wdl) workflow, and thereby exposing this optional input to the [Snippy_Streamline](https://github.com/theiagen/public_health_bioinformatics/blob/main/workflows/phylogenetics/wf_snippy_streamline.wdl) workflow
Whereas a bed file optional input can be used to mask an alignment in [Snippy_Tree](https://github.com/theiagen/public_health_bioinformatics/blob/main/workflows/phylogenetics/wf_snippy_tree.wdl), this input is not exposed as an option in [Snippy_Streamline](https://github.com/theiagen/public_health_bioinformatics/blob/main/workflows …

adding bed file input

---

tasks/utilities/task_kmc.wdl
workflows/theiaprok/wf_theiaprok_ont.wdl
workflows/utilities/wf_read_QC_trim_ont.wdl

KMC was failing on TheiaCoV_ONT even though the output is only used on TheiaProk_ONT.
This has been adjusted. Additionally, the kmc estimated genome size type has been adjusted to be `int` instead of a string
N/A
N/A
Tested locally on `miniwdl`
Underway

KMC on TheiaProk_ONT and TheiaCoV_ONT

---

.dockstore.yml
tasks/utilities/task_czgenepi_wrangling.wdl
tasks/utilities/task_download_terra_table.wdl
workflows/utilities/wf_czgenepi_prep.wdl

This PR introduces the CZGenEpi_Prep workflow which prepares data for upload to the Chan Zuckerberg GEN EPI platform, where phylogenetic trees and additional data processing can occur.
Many Terra users are doing this process manually, and so we thought to give them a hand.
1. Download Terra table
2. Extract desired samples
3. Extract desired columns
4. Reformat fasta file header and concatenate fasta file
5. Celebrate 🎉 
**Required**
- `sample_names` : array of sample ids
- `terra_project_name` : name of project
- `terra_table_name` : name of table where data is
- `terra_workspace_name` : name of workspace
**Optional**
There are many optional variables so the user can specify whatever they want. I have listed the defaults below as well.
- `assembly_fasta_column_name` = "assembly_fasta"
- …

CZGenEpi_Prep_PHB workflow

---

.github/workflows/pytest-workflows.yml
tasks/task_versioning.wdl
tests/config/environment.yml
tests/workflows/theiaprok/test_wf_theiaprok_illumina_pe.yml
tests/workflows/theiaprok/test_wf_theiaprok_illumina_se.yml

Updated `/tasks/task_versioning.wdl` which is used in many of the WDL workflows in PHB. This is a small but impactful change.
- exposed docker image as an optional input - just in case the user ever needs to change the docker (hopefully never)
- set default to GAR-hosted docker image `us-docker.pkg.dev/general-theiagen/ubuntu/ubuntu:jammy-20230816`
- Original image is `ubuntu:jammy-20230816` downloaded from dockerhub on 2023-09-28
Doesn't happen often, but occaisionally we see errors in Terra related to pulling docker images from dockerhub. It is said to be one of the least reliable docker image repo's as per the Broad developers.
This would update nearly all WDL workflows to pull from Theiagen's google artifact registry instead of dockerhub, in an attempt to reduce or eliminate the …

switch default docker image for version_capture to GAR-hosted image

---

tasks/utilities/task_augur_utilities.wdl
workflows/phylogenetics/wf_augur.wdl

Closes #211 
Due to failures, the `genes` and `colors` optional input files have been removed.
These changes will prevent workflow failure. 

Remove the genes and colors input files

---

tasks/taxon_id/task_kmerfinder.wdl
tasks/utilities/task_broad_terra_tools.wdl
tests/inputs/theiaprok/wf_theiaprok_illumina_pe.json
tests/inputs/theiaprok/wf_theiaprok_illumina_se.json
tests/workflows/theiacov/test_wf_theiacov_clearlabs.yml
tests/workflows/theiacov/test_wf_theiacov_fasta.yml
tests/workflows/theiacov/test_wf_theiacov_ont.yml
tests/workflows/theiaprok/test_wf_theiaprok_illumina_pe.yml
tests/workflows/theiaprok/test_wf_theiaprok_illumina_se.yml
workflows/theiacov/wf_theiacov_clearlabs.wdl
workflows/theiacov/wf_theiacov_fasta.wdl
workflows/theiacov/wf_theiacov_illumina_pe.wdl
workflows/theiacov/wf_theiacov_illumina_se.wdl
workflows/theiacov/wf_theiacov_ont.wdl
workflows/theiaprok/wf_theiaprok_fasta.wdl
workflows/theiaprok/wf_theiaprok_illumina_pe.wdl
workflows/theiaprok/wf_theiaprok_illumina_se.wdl
workflows/theiaprok/wf_theiaprok_ont.wdl

applied on wfs: theiacov clearlabs, fasta, ilmn pe, ilmn se, ont
Updates default `nextclade_dataset_tag` for sars-cov-2 to be up to date (as of 2023-10-10) across 5 TheiaCov workflows
Staying up-to-date. Specific to sars-cov-2 (as is many of the default inputs for TheiaCov workflows)
N/A
N/A
Did not test locally, will test all workflows in Terra

update default nextclade dataset tag to "2023-09-21T12:00:00Z" for all TheiaCov wfs

---

.github/PULL_REQUEST_TEMPLATE.md
tasks/task_versioning.wdl

This PR updates the template to better reflect our validation process. 

update template and update PHB version

---

tasks/species_typing/task_tbp_parser.wdl
tests/workflows/theiaprok/test_wf_theiaprok_illumina_pe.yml
tests/workflows/theiaprok/test_wf_theiaprok_illumina_se.yml
workflows/theiaprok/wf_theiaprok_illumina_pe.wdl
workflows/theiaprok/wf_theiaprok_illumina_se.wdl
workflows/theiaprok/wf_theiaprok_ont.wdl
workflows/utilities/wf_merlin_magic.wdl

This PR updates the default `tbp-parser` Docker image and introduces a new output -- the average depth.
Float `tbp_parser_average_genome_depth`

Update tbp-parser Docker and new output 

---

tasks/phylogenetic_inference/task_ksnp3.wdl
workflows/phylogenetics/wf_ksnp3.wdl

~~also added 1 new File output and change the output names to be more descriptive~~ See below for better description
~~Draft for now while we test in Terra~~
- added line break to 2 ksnp3 options for readability
- changed `mv` commands to rename the output VCF & TSV (SNPsNotinRef file) appropriately
- re-named output `File ksnp3_core_vcf` -> `File ksnp3_vcf_ref_genome`
- added 2 new outputs:
- `File ksnp3_vcf_snps_not_in_ref`
- `String ksnp3_vcf_ref_samplename` which is the samplename of the genome used to call SNPs
- re-named output `File ksnp3_core_vcf` -> `File ksnp3_vcf_ref_genome`
- added 2 new outputs:
- `File ksnp3_vcf_snps_not_in_ref`
- `String ksnp3_vcf_ref_samplename`
A user pointed out that the ksnp3 output File called `ksnp3_core_vcf` is misleading as these are not the core …

updated VCF output file renaming in kSNP3 task

---

tasks/taxon_id/task_midas.wdl
tests/workflows/theiaprok/test_wf_theiaprok_illumina_pe.yml
tests/workflows/theiaprok/test_wf_theiaprok_illumina_se.yml

made the un-tar/decompression of midas database (.tar.gz file) quiet since it produces 41k lines of output. 
When using the `tar -v` flag with this database, it results in a log file that is 2.7MB in size 😱 
also made the 2 `mv` commands verbose (but it's only 2 lines!)
lower storage cost, and task should run faster since it doesn't have to produce the 41k lines in the STDOUT
N/A
N/A
planning to only test in Terra since it's a simple code change
Test here ~~(still running as of 2023-10-06 afternoon) but I expect it to succeed~~ which ran successfully: https://app.terra.bio/#workspaces/theiagen-validations/curtis-sandbox-theiagen-validations/job_history/41fe3b0b-f92f-4f25-bcc0-d894090e2efe

reduce unnecessary logging in MIDAS task

---

tasks/gene_typing/task_amrfinderplus.wdl
tests/workflows/theiaprok/test_wf_theiaprok_illumina_pe.yml
tests/workflows/theiaprok/test_wf_theiaprok_illumina_se.yml

updates default docker image for amrfinderplus to `us-docker.pkg.dev/general-theiagen/staphb/ncbi-amrfinderplus:3.11.20-2023-09-26.1`
This is not the absolute latest version, but the more recent version 3.11.26 only adds a bug fix for a rare bug that does not affect our usage.
More importantly the database has not been updated since 2023-09-26, so we should be pretty up-to-date for the next few months
All TheiaProk workflows- ILMN PE, ILMN SE, ONT, FASTA
Standalone amrfinderplus workflow
N/A
N/A 
N/A
All outputs will be impacted as results may differ slightly due to database differences
Task ran successfully with `miniwdl`
~~Will add links when testing is complete~~
Good to test a variety of different species to try to trigger all of the `--organism` flag inputs. I have a dataset for …

update default amrfinderplus docker image to v3.11.20 and db 2023-09-26.1

---

tasks/assembly/task_irma.wdl
tests/inputs/theiacov/wf_theiacov_ont.json
workflows/theiacov/wf_theiacov_illumina_pe.wdl
workflows/theiacov/wf_theiacov_ont.wdl

Closes N/A
This PR adds an Influenza track onto the TheiaCoV_ONT_PHB workflow.
Uses the same IRMA task that performs assembly of influenza viruses but with module specification for ONT reads.
- TheiaCoV_ONT_PHB
- TheiaCoV_Illumina_PE
- IRMA task
Many public health laboratories are increasingly generating Oxford Nanopore data, hence the need for an influenza track to handle such inputs within 
Required inputs are:
`read1`
`samplename`
Recommended optional inputs:
`organism` - Required when analyzing pathogens other than SARS-CoV-2, e.g. "HIV" and "flu"
`primer_bed` - Was previously a required input, now an optional input as not required for flu analysis. However, it is required for other pathogens processed by the workflow such as HIV and SARS-CoV-2
`reference_genome` also required for HIV …

TheiaCoV_ONT_PHB Influenza Track

---

.dockstore.yml
tasks/utilities/task_theiacov_fasta_batch.wdl
workflows/theiacov/wf_theiacov_fasta_batch.wdl

This PR introduces a new workflow: TheiaCoV_FASTA_Batch.
No currently existing workflows and/or tasks will be impacted by this PR. The following new workflows/tasks have been added:
- TheiaCoV_FASTA_Batch task: `sm_theiacov_fasta_wrangling`
- TheiaCoV_FASTA_Batch workflow: `theiacov_fasta_batch`
The `dockstore.yml` file has also been edited to enable this workflow's access on Dockstore.
Occasionally, there is a need to run TheiaCoV_FASTA on thousands of samples at once. This results in the generation of thousands of VMs being created to run very short tasks. This workflow reduces the number of VMs made significantly as Pangolin4 and NextClade can both be run on multiple samples if provided a concatenated assembly file, leading to reduction of runtime costs.
**Note:** VADR is not yet …

TheiaCoV_FASTA_Batch: TheiaCoV_FASTA, for many samples at once

---

tasks/taxon_id/task_krona.wdl
workflows/metagenomics/wf_theiameta_illumina_pe.wdl

This PR adds new functionality to TheiaMeta: **[Krona Charts](https://github.com/marbl/Krona/wiki)**
Krona allows hierarchical data to be explored with zooming, multi-layered pie charts. 
On Terra, **an HTML file** is populated on the datatable that can be downloaded and explored on the browser interactively for both raw and read screen taxonomic assessment.  
Krona allows for the interactive visualization of the entire community at a high level. It also allows for to drill down for taxa of interest, keeping the taxonomic relationships. 
N/A
4 new outputs have been added to TheiaMeta:
```
String krona_version = krona_raw.krona_version
String krona_docker = krona_raw.krona_docker
File krona_html_raw = krona_raw.krona_html
File krona_html_clean = krona_clean.krona_html …
```

Add krona task to TheiaMeta_Illumina_PE

---

tasks/utilities/submission/task_mercury_file_wrangling.wdl
tasks/utilities/submission/task_submission.wdl
tasks/utilities/task_basespace_cli.wdl
tasks/utilities/task_broad_terra_tools.wdl
tasks/utilities/task_czgenepi_wrangling.wdl
tasks/utilities/task_download_terra_table.wdl
tasks/utilities/task_file_handling.wdl
tasks/utilities/task_ncbi_datasets.wdl
tasks/utilities/task_summarize_data.wdl
tasks/utilities/task_theiacov_fasta_batch.wdl
tasks/utilities/task_validate.wdl
tests/workflows/theiaprok/test_wf_theiaprok_illumina_pe.yml
tests/workflows/theiaprok/test_wf_theiaprok_illumina_se.yml

~~Need to test in Terra, but wanted to at least get the draft PR in place.~~
Testing is done in Terra, ready for review and further testing. I would recommend that the reviewer re-launches workflows on the dev branch `cjk-disable-call-cache` for workflows that have been run previously. If you don't have previous workflows, launch the workflow twice. Ensure the call cache box IS CHECKED (default behavior) and inspect job manager to ensure cache was not used for the updated WDL tasks
Closes #250 #235 
Added this code to a few different task files:
```WDL
meta {
volatile: true
}
```
So that call caching is disabled when running these workflows in Terra. In my opinion these are workflows where the expected behavior is to always run from the beginning, regardless of previous attempts.
The …

disable call caching for various workflows

---

tasks/utilities/submission/task_mercury_file_wrangling.wdl

Closes #186 
This PR:
- prints the excluded_samples.tsv to the log file because when the workflow fails, Terra likes to delete the file so the helpful information included is never seen and is no longer helpful
In addition, since the log file was becoming unwiedly, this PR also:
- updates the Docker image to the latest version so whenever a `gsutil` command is used, a warning isn't printed which inflates the log file unreasonably
- updates all `gsutil cp` commands to `gcloud storage cp` in order to keep in line with the latest Google recommendations
- Mercury_Prep_N_Batch
- `sm_metadata_wrangling`
Troubleshooting this workflow was becoming difficult when the issue resulted from missing metadata. By printing out this file to the log, this will ease troubleshooting significantly.
No new …

Mercury_Prep_N_Batch: print the excluded_samples.tsv and update Docker to avoid Google SDK warning

---

tasks/taxon_id/task_nextclade.wdl
tests/workflows/theiacov/test_wf_theiacov_clearlabs.yml
tests/workflows/theiacov/test_wf_theiacov_fasta.yml
tests/workflows/theiacov/test_wf_theiacov_ont.yml
workflows/theiacov/wf_theiacov_clearlabs.wdl
workflows/theiacov/wf_theiacov_fasta.wdl
workflows/theiacov/wf_theiacov_illumina_pe.wdl
workflows/theiacov/wf_theiacov_illumina_se.wdl
workflows/theiacov/wf_theiacov_ont.wdl

1. Previously Nextclade_Lineage looked for a column header "lineage" to populate this variable, however this not what the lineage column is called for SARS-CoV-2 - it's called "Nextclade_pango". This led to the nextclade_lineage variable being NULL for SARS-CoV-2. Monkeypox uses "lineage" as the column name for its lineage data so the task now looks for "Nextclade_pango" in the column names if "lineage" is not found.  
You can find these edits in tasks\taxon_id\task_nextclade.wdl lines 142-153
```
with codecs.open("NEXTCLADE_LINEAGE", 'wt') as Nextclade_Lineage:
if 'lineage' in tsv_dict:
nc_lineage = tsv_dict['lineage']
if nc_lineage is None:
nc_lineage = ""
elif 'Nextclade_pango' in tsv_dict: # added elif statement
nc_lineage = tsv_dict['Nextclade_pango']
if nc_lineage is None: …
```

Nextclade Output Added

---

tasks/quality_control/task_hostile.wdl
workflows/theiacov/wf_theiacov_illumina_pe.wdl
workflows/theiacov/wf_theiacov_ont.wdl
workflows/utilities/wf_read_QC_trim_ont.wdl
workflows/utilities/wf_read_QC_trim_pe.wdl

NOTE: Merge https://github.com/theiagen/public_health_bioinformatics/pull/202 before merging this branch!!
Adding a new `hostile` task as the human reads removal (dehosting) tool for `TheiaCoV_ONT_PHB`, and an optional dehosting tool for `TheiaCoV_Illumina_PE_PHB`.
`task_hostile`
`wf_read_QC_trim_pe`
`TheiaCoV_Illumina_PE_PHB`
`wf_read_QC_trim_ont`
`TheiaCoV_ONT_PHB`
The current dehosting tool `ncbi-scrub` only works with illumina paired end reads, whereas `hostile` works with both illumina and oxford nanopore (ONT) reads. Therefore, we are implementing `hostile` for dehosting of reads in the `TheiaCoV_ONT_PHB` workflow.
For `TheiaCoV_Illumina_PE_PHB`, we are giving users the option to use hostile if so preferred.
The `hostile` task takes as input the variable `seq_method` to determine if …

HOSTILE: For TheiaCoV_Illumina_PE_PHB and TheiaCoV_ONT_PHB

---

tasks/phylogenetic_inference/augur/task_augur_refine.wdl

Closes #249 
Reverted the augur refine input `clock_filter_iqd` to previous default value of 4.
[task_augur_refine.wdl](https://github.com/theiagen/public_health_bioinformatics/compare/main...jro_augur_refine_patch?quick_pull=1#diff-c1b0f0dfdbec944a3653e04455558cfe577e8c3db0f2e05edee375fb8a656ee5)
The default was changed when working with monkeypox genomes, all clades and not just the outbreak clade IIb, where some crucial sequences in understanding the full evolutionary history of the pathogen were getting removed as outliers.
We are changing this back to the previous default of 4, which is perfect for SARS-CoV-2, but will advise users to change it accordingly depending on the pathogen, especially where genuine outliers (not sequencing or dating artefacts) are expected.
Pull Request (PR) …

Update task_augur_refine iqd back to 4

---

.dockstore.yml
tasks/utilities/task_rename_files.wdl
workflows/utilities/file_handling/wf_rename_PE_files.wdl
workflows/utilities/file_handling/wf_rename_fastq_files.wdl

Closes #266
This PR implements a new utility workflow as requested in #266. This workflow received a read file or a pair of read files (FASTQ), compressed or uncompressed, and returned a new, renamed and compressed FASTQ file for submission in GISAID. 
None, this is a new implementation
Requested by SFPHL
This is a sample-level workflow. If a reverse read (`read2`) is provided, the files get renamed to the provided `new_filename` input with the notation `<new_filename>_R1.fastq.gz` and `<new_filename>_R2.fastq.gz`. If only `read1` is provided, the file gets renamed to `<new_filename>.fastq.gz`. If a not-compressed file is provided, this gets compressed automatically by the workflow. ´
```
input {
File read1  
File? read2
String new_filename
}
```
`read1`: Mandatory input; Forward-facing …

[New Utility] Workflow to rename FASTQ files (non-destructive)

---

tasks/utilities/task_validate.wdl
workflows/utilities/wf_theiavalidate.wdl

~theiagen/theiavalidate#1 partially~
closes #281 
This PR moves the entirety of the TheiaValidate code into [its own repository](https://github.com/theiagen/theiavalidate). It also implements a few new features:
- a table outputting validation-criteria failures only
- a new input that can translate different column names between tables to enable comparison
- TheiaValidate_PHB
- the `task compare_two_tsvs` in task_validate.wdl is now `task theiavalidate`
The Python code was exceeding our limit of 100 lines in a task file so we decided to transfer all the code into its own repository. Also, some changes and enhancements had been requested highly and so were implemented as well.
Renamed inputs:
- `table1` -> `table1_name`
- `table2` -> `table2_name`
New outputs:
- `Boolean debug_output` - …

TheiaValidate_PHB: new features and new Docker image from TheiaValidate repository

---

workflows/theiacov/wf_theiacov_ont.wdl

Closes #270 
To prevent workflow failure when read screening fails, this PR coerces the File `assembly_fasta` output into a String. Outputs behave the same on Terra, but workflow failure no longer will occur.
Also, some redundant `?` were removed
- TheiaCoV_ONT
`""` cannot be evaluated as a File, but a File _can_ be evaluated as a String.
No change
No change
No new outputs
`String assembly_fasta`
No original failures (before change) in read screen: https://app.terra.bio/#workspaces/cdc-terra-resources/Theiagen_Wright_SC2_Sandbox/job_history/17bbd163-1949-431f-a745-b4d5c9d15193
Original failures (before change) in read screen: https://app.terra.bio/#workspaces/cdc-terra-resources/Theiagen_Wright_SC2_Sandbox/job_history/4443d283-9729-42f8-ae4b-596a13c1800d
- Samples that fail the read …

TheiaCoV_ONT: prevent failure by coercing files into strings

---

tasks/species_typing/task_ts_mlst.wdl
tests/workflows/theiaprok/test_wf_theiaprok_illumina_pe.yml
tests/workflows/theiaprok/test_wf_theiaprok_illumina_se.yml

Closes #262 
All Theiaprok workflows 
- TheiaProk_Illumina_PE
- TheiaProk_Illumina_SE
- TheiaProk_ONT
- TheiaProk_FASTA
This PR updates the mlst database sync with pubmlst as of January 2024
New docker container: `us-docker.pkg.dev/general-theiagen/staphb/mlst:2.23.0-2024-01` 
N/A
N/A
N/A
All mlst outputs
```
File? ts_mlst_results = ts_mlst.ts_mlst_results
String? ts_mlst_predicted_st = ts_mlst.ts_mlst_predicted_st
String? ts_mlst_pubmlst_scheme = ts_mlst.ts_mlst_pubmlst_scheme
String? ts_mlst_allelic_profile = ts_mlst.ts_mlst_allelic_profile
String? ts_mlst_version = ts_mlst.ts_mlst_version
File? ts_mlst_novel_alleles = ts_mlst.ts_mlst_novel_alleles
String? ts_mlst_docker = ts_mlst.ts_mlst_docker
```
Local test passed with no issue on the `mlst` task
~~Underway~~ 
- TheiaProk_FASTA_PHB: …

update docker to version tag 2.23.0-2024-01

---

tasks/taxon_id/task_gambit.wdl
tests/workflows/theiaprok/test_wf_theiaprok_illumina_pe.yml
tests/workflows/theiaprok/test_wf_theiaprok_illumina_se.yml

Closes #277 
Updating default gambit reference files (signatures and metadata) to v1.3.0 using a Theiagen hosted, requester-pay bucket. 
- workflows/theiaeuk/wf_theiaeuk_illumina_pe.wdl
- workflows/theiaprok/wf_theiaprok_fasta.wdl
- workflows/theiaprok/wf_theiaprok_illumina_se.wdl
- workflows/theiaprok/wf_theiaprok_illumina_pe.wdl
- workflows/standalone_modules/wf_gambit_query.wdl
- workflows/theiaprok/wf_theiaprok_ont.wdl
Sourcing from a requester-pay, us-central1 bucket will help to reduce egress fees currently incurred from the gs://theiagen-public-files/terra/gambit_files/1.1.0/* files. Also, utilizing the updated database files will help refine taxon mis-calls noted in previous GAMBIT database versions.
For the gambit task to function, it requires two references files as input: …

Update Gambit database files to version 1.3.0

---

tasks/utilities/task_broad_terra_tools.wdl
tests/workflows/theiaprok/test_wf_theiaprok_illumina_pe.yml
tests/workflows/theiaprok/test_wf_theiaprok_illumina_se.yml

Closes #298
This PR addresses an issue found during validation where the type for the krakrn2 report output was not being passed correctly to the export taxon table task. 
This has been patched. 
TheiaProk suite of workflows:
- TheiaProk_Illumina_PE
- TheiaProk_Illumina_SE
export taxon tables task was expecting a `File` input for the `kraken_report` but due to it being an optional output, it is being handled as a String by the Theiaprok workflow (SE and PE).
N/A
N/A
N/A
Set of 20 bacterial genomes with taxon tables task enabled, as well as kraken2 optional module (one expected failure due to SRA lite file format issue): https://app.terra.bio/#workspaces/theiagen-validations/Theiagen_Mendes_Sandbox/job_history/805a3537-a339-4b05-99bd-8ec4c1b18a32

[TheiaProk suite] Patch fix: change type of kraken2_report to be string in taxon_table task

---

tests/inputs/theiacov/wf_theiacov_fasta.json
tests/workflows/theiacov/test_wf_theiacov_fasta.yml
workflows/theiacov/wf_theiacov_fasta.wdl

This PR closes #304 
Came across this bug during 1.3.0 release validation testing. This impacts the TheiaCoV_FASTA_PHB workflow only.
Mpox samples were accidentally run through the `abricate` task which is an Influenza-specific task. Workflow succeeded, but running this task is inappropriate for non-Flu samples.
The workflow code change is so that abricate is only run if user sets `organism` to `flu` AND `flu_subtype` is not set by user or unknown
This will affect the behavior of the workflow(s) even if users don’t change any workflow inputs relative to the last version: **Yes**
Running this workflow on different occasions could result in different results, e.g. due to use of a live database, "latest" docker image, or stochastic …

theiacov_fasta wf logic change for flu

---

workflows/theiacov/wf_theiacov_fasta.wdl

Adding back the `vadr_num_alerts` string output to theiacov_fasta workflow. It appears that this output was accidentally removed in PR #194 and went unnoticed until we ran the TheiaValidate workflow for the 1.3.0 release.
This PR closes #306 
Nothing has changed, we are just re-adding an output column to the workflow
Docker/software or software versions changed: N/A
Databases or database versions changed: N/A
Data …

restore vadr_num_alerts string output to theiacov_fasta workflow

---

tasks/assembly/task_irma.wdl
workflows/theiacov/wf_theiacov_illumina_pe.wdl

This PR closes #313.
This PR adds the `assembly_mean_coverage` metrics for influenza HA and NA in the `TheiaCoV_Illumina_PE_PHB` workflow which was previously only available for other pathogens.
This will affect the behavior of the workflow(s) even if users don’t change any workflow inputs relative to the last version : Yes (An output in `assembly_mean_coverage` where organism is "flu" that was previously empty)
Running this workflow on different occasions could result in different results, e.g. due to use of a live database, "latest" docker image, or stochastic data processing : Yes (Though not as a result of this specific PR)
Docker/software or software versions changed: N/A
Databases or database versions changed: N/A …

Adding `assembly_mean_coverage` metrics for flu in TheiaCoV_Illumina_PE_PHB

---

.github/workflows/miniwdl-check.yml
.github/workflows/pytest-workflows.yml
tasks/species_typing/task_pangolin.wdl
tasks/task_versioning.wdl
tests/config/environment.yml
tests/inputs/theiacov/wf_theiacov_fasta.json
tests/workflows/theiacov/test_wf_theiacov_clearlabs.yml
tests/workflows/theiacov/test_wf_theiacov_fasta.yml
tests/workflows/theiacov/test_wf_theiacov_illumina_pe.yml
tests/workflows/theiacov/test_wf_theiacov_illumina_se.yml
tests/workflows/theiacov/test_wf_theiacov_ont.yml
tests/workflows/theiaprok/test_wf_theiaprok_illumina_pe.yml
tests/workflows/theiaprok/test_wf_theiaprok_illumina_se.yml

~~Will fill this out later, just want to get the CI running to test these changes~~
This PR closes #324 
This PR is spun out of the CI failures we were seeing with `cromwell` test workflows over in PR #305 just prior to the v1.3.0 release.
TL;DR is that Pangolin, and in particular `scorpio` which runs as part of `pangolin` was being fed super-long paths from `cromwell`. The python `multiprocessing` package which `scorpio` uses struggles with these long paths, leading to failures that we had not seen before.
So this PR serves 2 purposes:
1. Update the Pangolin task to use `TMPDIR=/tmp` which leads to shorter paths, and force the usage of `pangolin --tempdir /tmp` option so that temporary file paths are shorter.
2. Update our CI to …

pangolin TMPDIR add and CI updates & improvements

---

tasks/utilities/task_theiacov_fasta_batch.wdl
workflows/theiacov/wf_theiacov_fasta_batch.wdl

removed required string inputs `seq_method` and `input_assembly_method` since they are not used in the workflow. They are not required.
This PR closes #320 
🗑️ This dev branch should **NOT** be deleted after merging to main (one potential PHL user)
described in issue #320 
These changes are to ease the usage of this workflow.
This will affect the behavior of the workflow(s) even if users don’t change any workflow inputs relative to the last version : **Yes, `seq_method` and `input_assembly_method` will no longer be updated/overwritten after running this workflow**
Running this workflow on different occasions could result in different results, e.g. due to use of a live database, "latest" docker image, or stochastic data processing: **No, results should not change if identical versions of …

theiacov_fasta_batch_PHB wf improvements

---

.dockstore.yml
tasks/gene_typing/task_amrfinderplus.wdl
tasks/taxon_id/task_kraken2.wdl
tests/workflows/theiacov/test_wf_theiacov_clearlabs.yml
tests/workflows/theiaprok/test_wf_theiaprok_illumina_pe.yml
tests/workflows/theiaprok/test_wf_theiaprok_illumina_se.yml
workflows/standalone_modules/wf_kraken2_ont.wdl
workflows/utilities/wf_read_QC_trim_ont.wdl

Closes #167 
This PR implements a new task `kraken2_parse_classified` that takes as input the classified reads file from Kraken2, alongside the Kraken2 report. This task computes the abundances based on fragment length for each taxon_id in the classified reads file, and parses the report to populate the taxon name. 
The new output report has the following structure: `Percent`, `Num_basepairs`, `Rank`, `Taxon_ID`, `Name`
As with Kraken2 report, the header is not included.
```
98.38943139373141	13934600	U	0	unclassified
0.08279494729112387	11726	D	10239	  Viruses
0.08229363045182063	11655	K	2731360	      Heunggongvirae
0.04975040070043142	7046	C	2731619	          Caudoviricetes
0.33614353195365293	47607	S	2859072	                Vibrio phage BUCT194
0.009560323949529397	1354	S	2886042 …
```

[Kraken2] Add module to recalculate abundances based on fragment length - Kraken2_ont wf and TheiaCoV_ONT wf

---

tasks/alignment/task_bwa.wdl
workflows/theiacov/wf_theiacov_illumina_pe.wdl
workflows/theiacov/wf_theiacov_illumina_se.wdl
workflows/utilities/wf_ivar_consensus.wdl

Closes #242 
This dev branch should NOT be deleted after merging, we need to notify Alex E. and recommend switching to `main` branch for further usage before deleting it
- expose `memory` and `docker` as optional inputs
- added functionality to cope with uncompressed FASTQ files used as input
- added lots of `echo` statements throughout to help with debugging and troubleshooting (we should keep these, they will be useful in the future)
- **IMPORTANT CHANGES** 
- lines 41-48 Altered the main `bwa` command to produce a sorted SAM file as output. Also pass in `cpus` to speed things up
- lines 51-56 added `samtools view` command to produce a BAM that ONLY includes **aligned reads**
- lines 59-64 added `samtools view` command to produce a BAM that ONLY includes **unaligned reads**
- lines …

output unaligned FASTQ files TheiaCov_Illumina PE and SE

---

tasks/phylogenetic_inference/augur/task_augur_clades.wdl
tasks/utilities/task_augur_utilities.wdl
workflows/phylogenetics/wf_augur.wdl

This PR closes #234!
This will affect the behavior of the workflow(s) even if users don’t change any workflow inputs relative to the last version : Yes
- The ncov repo commit change will cause all future *SARS-CoV-2* Augur trees to be built with updated lineages and clades as of 2024-02-01.
in the `set_sc2_defaults` task, the `nextstrain_ncov_repo_commit` was updated from "23d1243127e8838a61b7e5c1a72bc419bf8c5a0d" to "cec4fa0ecd8612e4363d40662060a5a9c712d67e" which differ …

[Augur_PHB] Update ncov repo commit and remove reference input to augur clades task

---

tasks/quality_control/task_qc_check_phb.wdl
tasks/taxon_id/task_midas.wdl
tasks/utilities/task_broad_terra_tools.wdl
tests/workflows/theiaprok/test_wf_theiaprok_illumina_pe.yml
tests/workflows/theiaprok/test_wf_theiaprok_illumina_se.yml
workflows/theiaprok/wf_theiaprok_illumina_pe.wdl
workflows/theiaprok/wf_theiaprok_illumina_se.wdl
workflows/utilities/wf_read_QC_trim_pe.wdl
workflows/utilities/wf_read_QC_trim_se.wdl

Closes https://github.com/theiagen/public_health_bioinformatics/issues/247
./tasks/taxon_id/task_midas.wdl
./tasks/quality_control/task_qc_check.wdl
./tasks/utilities/task_broad_terra_tools.wdl
./workflows/theiaprok/wf_theiaprok_illumina_se.wdl
./workflows/theiaprok/wf_theiaprok_illumina_pe.wdl
./workflows/utilities/wf_read_QC_trim_se.wdl
./workflows/utilities/wf_read_QC_trim_pe.wdl
This PR exposes the absolute coverage of the second-most prevalent genus detected by MIDAS in a sample. It also makes MIDAS a default module so that contamination is more easily identifiable. 
The MIDAS task performs the following steps: 
1. orders the MIDAS report by the relative abundance column
2. identifies the most prevalent genus by relative abundance
3. identifies the second-most prevalent genus by …

Expose midas secondary genus absolute coverage

---

tasks/utilities/data_import/task_basespace_cli.wdl
tasks/utilities/task_rasusa.wdl
tests/workflows/theiaprok/test_wf_theiaprok_illumina_pe.yml
tests/workflows/theiaprok/test_wf_theiaprok_illumina_se.yml
workflows/theiaprok/wf_theiaprok_fasta.wdl
workflows/theiaprok/wf_theiaprok_illumina_pe.wdl
workflows/theiaprok/wf_theiaprok_illumina_se.wdl
workflows/theiaprok/wf_theiaprok_ont.wdl

This PR closes #280, closes #370 and closes #359.
This PR does three things:
1. Provides a user input for users to turn off plasmidfinder
2. Hides the preemptible input parameter for BaseSpace_Fetch (no testing required except for checking the inputs of the workflow on Terra)
3. Disables call caching on RASUSA 
This will affect the behavior of the workflow(s) even if users don’t change any workflow inputs relative to the last version : Yes (call caching off on RASUSA)
Running this workflow on different occasions could result in different results, e.g. due to use of a live database, "latest" docker image, or stochastic data processing : Yes (RASUSA is random, but we only want to test to see if call caching is actually off
- …

[TheiaProk] Enable plasmidfinder to be skipped 

---

tasks/species_typing/pseudomonas/task_pasty.wdl
tests/workflows/theiaprok/test_wf_theiaprok_illumina_pe.yml
tests/workflows/theiaprok/test_wf_theiaprok_illumina_se.yml

This PR closes #232 
Upgrade to pasty v1.0.3 to avoid rare errors like those shown in issue #232 
`pasty` is run as a Pseudomonas aeurginosa-specific typing tool and is part of the Merlin_magic subworkflow. Since this is a task level change, only testing of one TheiaProk workflow is necessary (ILMN PE), but in theory **all TheiaProk workflows are impacted** since they may run the pasty task.
This will affect the behavior of the workflow(s) even if users don’t change any workflow inputs relative to the last version : **No**
The only change here is the …

upgrade pasty to v1.0.3

---

tasks/utilities/data_import/task_basespace_cli.wdl

Updated basespace_fetch WDL task to use the correct bash variable `$project_id` to enable server-side (in other words basespace-side) filtering, previously the code was set to use a different bash variable `$run_id`, which was incorrect. 
This section of the code is only triggered when `$run_id` was explicitly NOT set, meaning that the variable was empty, meaning the `--project-id` flag was not used at all in the one-liner on line 53 of the WDL task. 
When that flag is not used, there is no filtering done on the response, which means very slow responses from basespace for Basespace accounts that have LOTS (>1000s) of datasets in basespace.
So when the `bs list dataset --project-id=${run_id}` command was run, it essentially equated to (see the blank?):
```
bs list dataset --project-id= | …
```

bug fix to BaseSpace_Fetch_PHB

---

tasks/species_typing/multi/task_ts_mlst.wdl
tests/workflows/theiaprok/test_wf_theiaprok_illumina_pe.yml
tests/workflows/theiaprok/test_wf_theiaprok_illumina_se.yml

This PR closes #373 
This pull request updates ts_mlst docker container to update its database to the latest version available (2024-03-11). This is in preparation for the next release.
Docker/software or software versions changed: Yes, updated to the latest version (2024-03-11)
Databases or database versions changed: Yes, updated to the latest version (2024-03-11)
Data processing/commands changed: None
File processing …

[TheiaProk] update ts_mlst docker image to latest release available (2024-03-11)

---

.github/workflows/pytest-workflows.yml
tests/config/pytest_filter.yml
tests/workflows/theiacov/test_wf_theiacov_clearlabs.yml
tests/workflows/theiacov/test_wf_theiacov_fasta.yml
tests/workflows/theiacov/test_wf_theiacov_illumina_pe.yml
tests/workflows/theiacov/test_wf_theiacov_illumina_se.yml
tests/workflows/theiacov/test_wf_theiacov_ont.yml
workflows/utilities/wf_organism_parameters.wdl

This PR closes #390 
Update default docker image used for running `pangolin` across all TheiaCov workflows & Pangolin_update standalone workflow
**Updated the default docker image in organism_parameters subwf. tested successfully with `miniwdl`**
Running this workflow on different occasions could result in different results, e.g. due to use of a live database, "latest" docker image, or stochastic data processing : **No**
Nothing has changed other than the docker image
Docker/software or software versions changed: `us-docker.pkg.dev/general-theiagen/staphb/pangolin:4.3.1-pdata-1.25.1` ➡️ …

update default pangolin docker image to image with pangolin-data v1.26

---

tasks/quality_control/advanced_metrics/task_busco.wdl
tests/workflows/theiaprok/test_wf_theiaprok_illumina_pe.yml
tests/workflows/theiaprok/test_wf_theiaprok_illumina_se.yml
workflows/theiaeuk/wf_theiaeuk_illumina_pe.wdl
workflows/theiaprok/wf_theiaprok_fasta.wdl
workflows/theiaprok/wf_theiaprok_illumina_pe.wdl
workflows/theiaprok/wf_theiaprok_illumina_se.wdl
workflows/theiaprok/wf_theiaprok_ont.wdl

This PR closes #345 
Update BUSCO to the latest available version
This will affect the behavior of the workflow(s) even if users don’t change any workflow inputs relative to the last version : **Yes, BUSCO task auto-downloads their database at runtime and it is periodically updated (not sure how often but last update for enterobacteriales db was 2024-01-08**
Running this workflow on different occasions could result in different results, e.g. due to use of a live database, "latest" docker image, or stochastic data processing : **Yes** 
Impacted workflows:
- All TheiaProk workflows (ILMN PE, ILMN SE, ONT, FASTA)
- TheiaEuk_illumina_pe_phb
Docker/software or software versions changed: **upgraded to use a Theiagen-hosted copy of the …

update BUSCO to v5.7.1 and small tweaks to WDL task

---

workflows/theiacov/wf_theiacov_illumina_pe.wdl
workflows/theiacov/wf_theiacov_ont.wdl

This PR closes #405 
The TheiaCoV_Illumina_PE_PHB and TheiaCoV_ONT_PHB workflows run Nextclade on the NA segment, which provides a clade for this segment, but this output is not populated back to the Terra data table unfortunately. You will have to look into the output files on the step that is specific to running nextclade on the NA segment. 
Additionally, the output files produced by nextclade (auspice_input_json, nextclade_json, nextclade_tsv) are not populated back to the Terra data table either.
And lastly, the `nextclade_qc` output string is also not populated to the Terra data table.
This will affect the behavior of the workflow(s) even if users don’t change any workflow inputs relative to the last version : **No**
Running …

add Flu NA Nextclade outputs to theiacov_illumina_pe

---

tests/workflows/theiacov/test_wf_theiacov_clearlabs.yml
tests/workflows/theiacov/test_wf_theiacov_fasta.yml
tests/workflows/theiacov/test_wf_theiacov_illumina_pe.yml
tests/workflows/theiacov/test_wf_theiacov_illumina_se.yml
workflows/utilities/wf_organism_parameters.wdl

~~Will update this PR message later.~~
~~This PR closes #<Issue number>.~~
Update to latest nextclade_dataset tag that was released for SARS-CoV-2 today: https://github.com/nextstrain/nextclade_data/releases/tag/2024-04-15--15-08-22Z
This will impact all workflows that run nextclade on sars-cov-2 samples (so all TheiaCoV workflows)
Running this workflow on different occasions could result in different results, e.g. due to use of a live database, "latest" docker image, or stochastic data processing: **No** 
Docker/software or software versions changed: **N/A**
Databases or database versions …

update to latest nextclade_dataset release for SC2 `2024-04-15--15-08-22Z`

---

workflows/theiacov/updates/wf_pangolin_update.wdl

Removing these inputs as they are unused and only appear because they are part of the organism_parameters subwf. So we are setting some default values to hide the options in Terra

pangolin_update wf: hide unused input params for vadr

---

tasks/taxon_id/contamination/task_midas.wdl
tests/workflows/theiaprok/test_wf_theiaprok_illumina_pe.yml
tests/workflows/theiaprok/test_wf_theiaprok_illumina_se.yml

This PR closes #447 
Changed default `midas_db` (required for running Midas) to a requester-pays bucket location to save on costs. The user's GCP account/GCP project will assume the cost of using this database when running TheiaProk workflows
This will affect the behavior of the workflow(s) even if users don’t change any workflow inputs relative to the last version : **No**
**Nothing has changed except the location of the midas_db. It's the same db as before**
Docker/software or software versions changed: **No** …

update default midas_db location to requester pays bucket

---

.dockstore.yml
tasks/quality_control/advanced_metrics/task_gambittools.wdl
workflows/standalone_modules/wf_gambitcore.wdl

This PR closes #328
This new workflow is an implementation of the gambitcore utility, available at https://github.com/gambit-suite/gambitcore. 
> This application takes in assemblies, identifies the species, then calculates the completeness of the assemblies against the species core genome. This is a good quality control step. It is acheived by looking at the GAMBIT k-mers in the assembly and comparing them to the GAMBIT k-mers in the core genome. If the assembly is poor quality, it is expected that the completeness of the assembly will be lower.
The container for this utility is available at `us-docker.pkg.dev/general-theiagen/internal/gambitcore:0.0.1`
The GAMBIT metadata and signatures files is required for gambitcore, …

[New workflow - internal] Gambitcore for assembly quality assessment with GAMBIT

---

tasks/assembly/task_shovill.wdl
tasks/phylogenetic_inference/task_ksnp3.wdl
tasks/quality_control/advanced_metrics/task_busco.wdl
tasks/quality_control/basic_statistics/task_cg_pipeline.wdl
tasks/quality_control/comparisons/task_screen.wdl
tasks/task_versioning.wdl
tasks/taxon_id/contamination/task_midas.wdl
tasks/taxon_id/task_gambit.wdl
tests/workflows/theiaprok/test_wf_theiaprok_illumina_pe.yml
tests/workflows/theiaprok/test_wf_theiaprok_illumina_se.yml
workflows/utilities/wf_read_QC_trim_pe.wdl
workflows/utilities/wf_read_QC_trim_se.wdl

This one is a doozy. 
This PR:
- closes #483
- closes #485 
- closes #487 
- closes #488 
- closes #489 
- closes #490 
- closes #491 
- closes #492 
- closes #493 
Many tasks require far more runtime parameters than are actually used. This PR adjusts various runtime parameters accordingly.
- No change in workflow function, just optimization of resources
- many, see also code changes
None 
None
Ensure …

[Internal] Updating runtime parameters

---

tasks/alignment/task_mafft.wdl
tasks/assembly/task_irma.wdl
workflows/theiacov/wf_theiacov_illumina_pe.wdl
workflows/theiacov/wf_theiacov_ont.wdl

~~Starting a draft while doing testing in Terra. Will update this message periodically~~
This PR closes #412 closes #437 and closes #457
The aim of this PR is to resolve a few different issues/bugs and make general improvements & upgrades to the TheiaCoV workflows for Flu analysis. Much of these changes impact the IRMA task, used in TheiaCoV_Illumina_PE wf, but some changes impact other workflows like TheiaCoV_ONT for Flu analysis.
Running this workflow on different occasions could result in different results, e.g. due to use of a live database, "latest" docker image, or stochastic data processing …

IRMA bug fixes & improvements; theiacov_illumina_pe wf updates for Flu

---

tasks/phylogenetic_inference/augur/task_augur_export.wdl
tasks/phylogenetic_inference/augur/task_augur_refine.wdl
tasks/phylogenetic_inference/augur/task_augur_traits.wdl
tasks/utilities/data_handling/task_augur_utilities.wdl
workflows/phylogenetics/wf_augur.wdl
workflows/phylogenetics/wf_augur_prep.wdl

This PR closes #458.
This PR features updates to the Augur_Prep_PHB and Augur_PHB workflows enabling a user to run these workflows with only the sequence information and not requiring associated metadata. The use case is such as when a user needs to only generate a distance tree in the newick format.
At present, in addition to sequence data, one can only run Augur_Prep_PHB when continent, country, state and collection date information is available. After this update, only the sequence information will be required.
For Augur_PHB workflow, in addition to assemblies and build name, associated metadata is a requirement. With this update, only the assemblies and build name will be required.
This will affect the behavior of the …

Augur_PHB: Set sample_metadata_tsvs input to optional

---

tasks/gene_typing/drug_resistance/task_amrfinderplus.wdl
tests/workflows/theiaprok/test_wf_theiaprok_illumina_pe.yml
tests/workflows/theiaprok/test_wf_theiaprok_illumina_se.yml

This PR closes #511 
🗑️ This dev branch should  be deleted after merging to main.
- update default docker image for amrfinderplus
- reduce default compute resources & enable preemptible VMs to be used (cheaper)
**Workflows impacted**
- TheiaProk_illumina_PE
- TheiaProk_illumina_PE
- TheiaProk_ONT
- TheiaProk_FASTA
- NCBI-AMRFinderPlus_PHB
Docker/software or software versions changed: v3.11.20 & DB v2023-09-26.1 ➡️ v3.12.8 & DB v2024-05-02.2 …

[TheiaProk] Update amrfinderplus to v3.12.8; DB: v2024-05-02.2; reduce compute resources

---

tasks/species_typing/multi/task_ts_mlst.wdl
tests/workflows/theiaprok/test_wf_theiaprok_illumina_pe.yml
tests/workflows/theiaprok/test_wf_theiaprok_illumina_se.yml

This PR closes #510
- upgrade default docker image to StaPH-B's June 2024 build of the `mlst` docker image
- reduce compute resources requested & enabled premptible VMs. `mlst` is super lightweight (runs very fast) and only needs 1 cpu.
This will affect the behavior of the workflow(s) even if users don’t change any workflow inputs relative to the last version : **Yes, if the mlst scheme has changed for the given organism**
Impacted workflows:
- TheiaProk_illumina_pe
- TheiaProk_illumina_se
- TheiaProk_ont
- TheiaProk_fasta
Docker/software or software …

[TheiaProk] upgrade mlst docker image to 2024-06-01 staphb build; reduced runtime parameters; enable preemptible

---

tasks/species_typing/streptococcus/task_emmtyper.wdl
tasks/utilities/data_export/task_broad_terra_tools.wdl
tests/workflows/theiaprok/test_wf_theiaprok_illumina_pe.yml
tests/workflows/theiaprok/test_wf_theiaprok_illumina_se.yml
workflows/theiaprok/wf_theiaprok_fasta.wdl
workflows/theiaprok/wf_theiaprok_illumina_pe.wdl
workflows/theiaprok/wf_theiaprok_illumina_se.wdl
workflows/theiaprok/wf_theiaprok_ont.wdl
workflows/utilities/wf_merlin_magic.wdl

This PR closes #413.
This PR adds [emmtyper](https://github.com/MDU-PHL/emmtyper) to the TheiaProk workflows to perform emm gene typing on Streptococcus pyogenes assemblies. TheiaProk_Illumina_PE_PHB already contains a similar task using the read-based [emmtyping_tool](https://github.com/ukhsa-collaboration/emm-typing-tool), which is only compatible with paired-end reads. Since emmtyper works on assemblies, it is compatible with the paired-end, single-end, FASTA, and ONT versions of the TheiaProk workflows. Also, there are sometimes differences between the two tools' outputs (see validation test results below), so I think it is useful to make both tools available.
This will affect the behavior of the workflow(s) even if …

[TheiaProk] Add emmtyper task for Streptococcus pyogenes

---

tasks/utilities/data_import/task_sra_fetch.wdl

This PR closes #480 
In SRA-Lite format, reject reads have a set quality encoding of 3, which is represented by the '$' character. This was not taken into consideration by our previous attempt to auto-detect this format by checking the quality-encoding range.
This is a fix to also report SRA-Lite when just the `?` or `$` characters are detected in the first line of quality-encoding characters. 
**Note:** If the read quality only contains `?` and `$` characters, it will be reported as SRA-Lite. Given that one encodes for Q-30 and the other for Q-3, it is extremely unlikely that this would occur naturally. 
This will affect the behavior of the workflow(s) even if users don’t change any workflow inputs relative to the last …

[SRA-Fetch] Detect SRA-Lite when it's low quality file

---

tasks/utilities/data_import/task_create_terra_table.wdl

This PR closes #534.
Fastq files that end in .fq were not recognized. This PR fixes this.

[Create_Terra_Table] recognize fastq files that end in .fq

---

.github/PULL_REQUEST_TEMPLATE.md
tasks/gene_typing/drug_resistance/task_amrfinderplus.wdl
tests/workflows/theiaprok/test_wf_theiaprok_illumina_pe.yml
tests/workflows/theiaprok/test_wf_theiaprok_illumina_se.yml

This PR closes #129 
This PR adds support for using the `amrfinder --organism <organism_name>` option for 3 new organisms (Vv, Vp, and Enterobacter asburiae) and corrects a typo for C. diff.
These are organisms that were recently added to NCBI AMRFinderPlus' list of supported organisms that have taxon-specific point mutations or other organism-specific handling of annotation: https://github.com/ncbi/amr/wiki/Running-AMRFinderPlus#--organism-option
When users analyze these samples via the TheiaProk workflows (or the standalone amrfinderplus workflow), AMRFinderPlus will now use the `--organism` flag and be able to detect organism-specific point mutations.
The usage of the `amrfinder --organism` option depends on GAMBIT accurately …

[theiaprok] amrfinderplus: add support for Vibrio parahaemolyticus, Vibrio vulnificus, Enterobacter asburiae. Fix C diff bug

---

tests/workflows/theiaprok/test_wf_theiaprok_illumina_pe.yml
tests/workflows/theiaprok/test_wf_theiaprok_illumina_se.yml
workflows/utilities/wf_merlin_magic.wdl

This PR closes #273 
🗑️ This dev branch should  be deleted after merging to main.
This PR resolves a minor bug described in https://github.com/theiagen/public_health_bioinformatics/issues/273
The code change allows for Shigella sonnei samples to also be run through the virulencefinder task. Previously they were excluded due to the conditionals in the merlin_magic subworkflow.
With this change, all Shigella sonnei samples will be run through virulencefinder (along with all E. coli and other non-sonnei Shigella species like flexneri, dysenteriae, boydii)
This will affect the behavior of the workflow(s) even if users don’t change any workflow inputs relative to the last version : **Yes, slightly for S sonnei samples**
Running this workflow on different occasions could result in different …

[TheiaProk] Merlin_magic subwf bugfix: run virulencefinder on Shigella sonnei

---

tasks/quality_control/read_filtering/task_ncbi_scrub.wdl
tests/workflows/theiacov/test_wf_theiacov_illumina_se.yml
tests/workflows/theiaprok/test_wf_theiaprok_illumina_se.yml
workflows/utilities/wf_read_QC_trim_pe.wdl
workflows/utilities/wf_read_QC_trim_se.wdl

This PR closes #127 and #528
~~Current work in progress! Will update soon!~~
This PR updates [HRRT](https://github.com/ncbi/sra-human-scrubber) (also known as ncbi-scrub) to the **latest stable version v2.2.1**.
This update aims to correct a few issues:
- The paired-information was not being kept with the current processing
- The reads were being masked with 'N' instead of removed, which could save a lot of compute resources downstream
The following editions were done to the `ncbi_scrub` task:
- docker has been updated to `us-docker.pkg.dev/general-theiagen/ncbi/sra-human-scrubber:2.2.1`
- In the `ncbi_scrub_pe` task,  the reads are now interleaved before processing with HRRT
- In the `ncbi_scrub_pe` task, the option to …

[TheiaCoV and TheiaMeta] Update hrrt (ncbi-scrub) to version 2.2.1 and optimise task

---

.github/workflows/pytest-workflows.yml
tasks/quality_control/advanced_metrics/task_vadr.wdl
tests/workflows/theiacov/test_wf_theiacov_clearlabs.yml
tests/workflows/theiacov/test_wf_theiacov_fasta.yml
tests/workflows/theiacov/test_wf_theiacov_illumina_pe.yml
tests/workflows/theiacov/test_wf_theiacov_illumina_se.yml
tests/workflows/theiacov/test_wf_theiacov_ont.yml
workflows/theiacov/updates/wf_vadr_update.wdl
workflows/theiacov/wf_theiacov_clearlabs.wdl
workflows/theiacov/wf_theiacov_fasta.wdl
workflows/theiacov/wf_theiacov_illumina_pe.wdl
workflows/theiacov/wf_theiacov_illumina_se.wdl
workflows/theiacov/wf_theiacov_ont.wdl

This PR closes #464
This PR updates the default VADR docker image to one that includes the most up-to-date VADR model files for Influenza `v1.6.3-2` (previous docker image included influenza models `v1.6.3-1`). Changes are described here: https://bitbucket.org/nawrockie/vadr-models-flu/src/master/00RELEASE-NOTES.txt This model version will likely be used by NCBI for screening Flu genomes submitted to GenBank in the future, when they stop using FLAN.
A more in-depth explanation of the creation of the VADR model files for Influenza can is described in this pre-print (will likely be published soon): https://www.biorxiv.org/content/10.1101/2024.03.21.585980v1
VADR docs on Flu usage: …

[theiacov] Add additional vadr output files & tarball; upgrade VADR docker

---

tasks/utilities/data_export/task_broad_terra_tools.wdl
tests/workflows/theiaprok/test_wf_theiaprok_illumina_pe.yml
tests/workflows/theiaprok/test_wf_theiaprok_illumina_se.yml
workflows/theiacov/wf_theiacov_ont.wdl
workflows/theiaprok/wf_theiaprok_ont.wdl
workflows/utilities/wf_read_QC_trim_ont.wdl

This PR closes #203 
This PR removes the KMC module from the TheiaCoV and TheiaProk ONT workflows. In place of the estimated genome length in TheiaProk ONT, I have added a default genome length of 5 Mb, which is around .7 Mb larger than the average genome length as estimated by calculating the mean genome length of all bacteria included in [this](https://github.com/CDCgov/phoenix/blob/main/assets/databases/NCBI_Assembly_stats_20240124.txt) file. 
TheiaProk_ONT and TheiaCoV_ONT
This PR may lead to different results in pre-existing outputs: **Yes**, assemblies generated may be different due to differences in the use of estimated genome length in RASUSA downsampling. 
This PR uses an element that could cause duplicate runs to have …

[ONT] Remove KMC

---

tasks/utilities/data_import/task_create_terra_table.wdl

This PR closes #580 
This PR resolves a bug where sample names that contained substrings of other sample names would not be properly identified. For example: if three samples were found with the following names and imported in the following order:
- 1000B1
- 1000B2
- 1000
The current behavior would fail to recognize that 1000 is not included in th table since it can find 1000 in the text for "1000B1" and "1000B2".
This PR fixes this by instructing grep to look at the entire word, not just a substring.
Tested …

[Create_Terra_Table] fix sample name identification bug

---

tasks/quality_control/read_filtering/task_ncbi_scrub.wdl
tasks/taxon_id/freyja/task_freyja.wdl
tasks/taxon_id/freyja/task_freyja_dashboard.wdl
tasks/taxon_id/freyja/task_freyja_plot.wdl
tasks/taxon_id/freyja/task_freyja_update.wdl
tasks/utilities/data_handling/task_fasta_utilities.wdl
tests/workflows/theiacov/test_wf_theiacov_illumina_se.yml
tests/workflows/theiaprok/test_wf_theiaprok_illumina_se.yml
workflows/freyja/wf_freyja_fastq.wdl
workflows/utilities/wf_read_QC_trim_se.wdl

This PR closes #546
This PR reworks the `Freyja_FASTQ` workflow to be technology-agnostic, allowing analysis with sequencing data from Illumina (paired-end and single-end) and ONT instruments (the first of it's kind!!!). 
Additionally, Freyja was updated to the latest version, `v1.5.1`:
- The barcodes file now is expected to be in the `.feather` format (see [here](https://github.com/andersen-lab/Freyja/releases/tag/v1.5.1))
- Additional optional inputs have been exposed for `freyja demix`
- This will affect the behavior of the workflow(s) even if users don’t change any workflow inputs relative to the last version : No if update if turned off and the same type of data is used.
- Running this workflow on different occasions …

[Freyja] - Update to version v1.5.1 and make it compatible with ILMN PE, ILMN SE and ONT

---

tasks/phylogenetic_inference/augur/task_augur_mutation_context.wdl
workflows/phylogenetics/wf_augur.wdl

This PR closes #499.
This PR adds the mutation fraction of G->A or C->T changes to the **Augur_PHB** output `auspice_input_json` when the organism is `MPXV`. These mutations have been shown to be a characteristic of APOBEC3-type editing, which indicate adaptation of the virus to circulation among humans as was observed with the 2022 clade IIb outbreak, and more recently with the clade I outbreak in South Kivu, Democratic Republic of the Congo.
This will affect the behavior of the workflow(s) even if users don’t change any workflow inputs relative to the last version : Yes, is organism is MPXV, there will be additional annotation in the auspice tree
Running this workflow on different occasions could result in different …

Add MPXV mutation context to Augur_PHB

---

docs/workflows/genomic_characterization/theiacov.md
tasks/assembly/task_ivar_consensus.wdl
tasks/gene_typing/variant_detection/task_ivar_variant_call.wdl
tests/workflows/theiacov/test_wf_theiacov_illumina_pe.yml
tests/workflows/theiacov/test_wf_theiacov_illumina_se.yml
workflows/utilities/wf_ivar_consensus.wdl

This PR closes #598 
The Ivar Consensus workflow was facing a silent error due to a pipefail on input files that were very large. 
The changes in this PR do the following:
1. Add pipefail parameters `set -euo pipefail` to both the ivar consensus task and the ivar variant calling task.
2. Expose `cpu`, `memory`, `disk_size`, and `docker` parameters for the following tasks in the ivar consensus wf:
- bwa alignment 
- primer trimming
- stats and coverage for primer trimming 
- variant calling
- consensus 
- stats and coverage for the consensus wf
3.Improve error handling so that tasks will now fail correctly instead of producing silent errors.
This PR may lead to different results in pre-existing outputs: No
This PR uses an …

[TheiaCoV] iVar Consensus Pipefail fix

---

docs/workflows/genomic_characterization/theiacov.md
docs/workflows/phylogenetic_construction/augur.md
workflows/phylogenetics/wf_augur.wdl
workflows/utilities/wf_organism_parameters.wdl

This PR closes #522 
Enables H5N1 analysis for the HA segment in both Augur and TheiaCoV workflows via the organism_parameters sub workflow.
- TheiaCoV
- Augur
- organism_parameters
For Augur & TheiaCoV a user can now input H5N1 as a `flu_subtype` when specifying `flu` as an organism which will trigger nextclade and augur to use `H5N1` configs for characterization and phylogenetic analysis. The nexstrain dataset is for HA segment only and there currently does not exist one for NA. 
For `wf_organism_parameters.wdl`  the following nested logic has been added for flu: …

[Augur  +TheiaCoV] Enable  H5N1 flu subtype augur & nextclade

---

docs/workflows/genomic_characterization/theiameta.md
tests/workflows/theiaprok/test_wf_theiaprok_illumina_pe.yml
workflows/theiameta/wf_theiameta_illumina_pe.wdl
workflows/utilities/wf_read_QC_trim_pe.wdl

This PR closes #308
This PR introduces conditional logic for MIDAS to run within the TheiaMeta workflow, adding additional QC through the integration of MIDAS for metagenomic data processing. Additionally, the workflow has been updated to allow for flexibility in handling theiaprok and theiameta as workflow series inputs.
- TheiaMeta Illumina PE workflow: The integration of MIDAS as a conditional QC step.
- wf_read_QC_trim_pe workflow: Updated logic for handling theiaprok and theiameta and adding MIDAS as a task.
This PR may lead to different results in pre-existing outputs: Yes
MIDAS-related outputs will now be available in runs where call_midas = true, which adds new outputs related to taxonomic identification and abundance …

[TheiaMeta] Midas call in read_QC_trim_pe.wdl workflow and outputs

---

docs/workflows/genomic_characterization/theiacov.md
tasks/assembly/task_irma.wdl

This PR closes #630 
PR updates TheiaCoV workflow for when "flu" organism is chosen, and reorders flue segments from largest to smallest in the irma task. 
wf: TheiaCov
task: task_irma
Changes take expected flu segment lengths (large to small) and concatenates them in the irma task to the irma consensus fasta in descending order
In task_irma.wdl for the flu track of TheiaCoV, the process for creating the consensus fasta was updated to order the flu segments from largest to smallest `segments=("PB2" "PB1" "PA" "HA" "NP" "NA" "MP" "NS")` as per request, updating …

[TheiaCoV] Reorder flu segments from largest to smallest in irma task

---

docs/workflows/public_data_sharing/mercury_prep_n_batch.md
tasks/utilities/submission/task_mercury.wdl

This PR closes #615 
Causes the task to fail if the Mercury script fails.
- Mercury_Prep_N_Batch
Adds `set -euo pipefail` to the top of the script to catch all potential errors so that the workflow fails as expected, preventing silent failures. Should greatly help in troubleshooting.
None
None
Testing [here](https://app.terra.bio/#workspaces/theiagen-validations/sage_viral/job_history/ebddd226-584b-4caa-9294-8711a81f6a06) with files that were already uploaded -- expecting error due to lack of deletion permissions.

[Mercury] prevent silent failures

---

docs/workflows/genomic_characterization/theiacov.md

This is just a type correction on the variable input_assembly_method from File to String no other changes

[Documentation] type error correction theiacov wf

---

docs/workflows/genomic_characterization/theiaprok.md

This PR updates the TheiaProk documentation to specify the use of the MIDAS v1.2 reference database as the default for bacterial species detection in metagenomic data. Minor adjustments for clarity were also made and indicate the user can also upload a custom database with link to midas github page to create new custom db

[Documentation] Update MIDAS database documentation in TheiaProk

---

tests/workflows/theiacov/test_wf_theiacov_clearlabs.yml
tests/workflows/theiacov/test_wf_theiacov_fasta.yml
tests/workflows/theiacov/test_wf_theiacov_illumina_pe.yml
tests/workflows/theiacov/test_wf_theiacov_illumina_se.yml
tests/workflows/theiacov/test_wf_theiacov_ont.yml
workflows/utilities/wf_organism_parameters.wdl

… parameters
This PR closes #669 
This PR updates nextclade dataset tags to the latest versions as of 12/3/2024, as well as bumping the pangolin docker from 1.29 -> 1.31. 
Aside, but along with this I made a utility to automatically check nextclade versions that need to be udpated. 
https://github.com/theiagen/utilities/blob/mb-nextclade-utility/scripts/nextclade-version-check.sh
The `wf_organism_parameters` has been updated. 
The following changes have been made for latest updates:
| Variable Name | Dataset Name | Latest Tag | Current Tag | …

[TheiaCoV] Update nextclade dataset tags and pangolin docker version

---

docs/workflows/genomic_characterization/theiacov.md
workflows/utilities/wf_organism_parameters.wdl

This PR closes #682 
Updates wf_organism_paramters ds tag for H5N1 HA segment
`wf_organism_paramters`
`h5n1_ha_nextclade_ds_tag` changed from old `2024-05-08--11-39-52Z` ds tag to new `2024-12-04--17-05-31Z` tag.
`h5n1_ha_nextclade_ds_tag` version bump for nextclade.
Tested specifically on h5n1 flu data [here](https://app.terra.bio/#workspaces/cdph-terrabio-taborda-manual/CDPH_Bioinformatics_Development/job_history/0b997d06-5597-4568-b30b-bd5cd49db1e8)
-This output of this will show the `2024-12-04--17-05-31Z` ds tag as well as NA segment being correctly identified. …

[TheiaCoV] Update nextclade dataset tag for H5N1 to the latest version

---

tasks/species_typing/vibrio/task_srst2_vibrio.wdl
tests/workflows/theiaprok/test_wf_theiaprok_illumina_pe.yml
tests/workflows/theiaprok/test_wf_theiaprok_illumina_se.yml
workflows/utilities/wf_merlin_magic.wdl

This PR closes #560
Removes prefix of srst2_ from inputs of srst2_vibrio task within wf_merlin_magic.
For each of the parameters within srst2_vibrio, the prefix of srst2_ was removed. This was then reflected within the command block as well as the call block of srst2_vibrio within wf_merlin_magic. 
|main|awh-srst2vibrio-dev|
|-----|----------------------|
|Int srst2_min_cov|Int min_cov|
|Int srst2_max_divergence|Int max_divergence|
|Int srst2_min_depth|Int min_depth|
|Int srst2_min_edge_depth|Int min_edge_depth|
|Int srst2_gene_max_mismatch|Int gene_max_mismatch|
```
main …
```

[srst2_vibrio, merlin_magic] Removed instances of srst2_ from inputs

---

tasks/gene_typing/variant_detection/task_ivar_variant_call.wdl
tests/workflows/theiacov/test_wf_theiacov_illumina_pe.yml
tests/workflows/theiacov/test_wf_theiacov_illumina_se.yml

This PR closes #716 
We have run into a few issues where data quality is bad ivar variants calling will fail after we most recently added `set -eou pipefail` to the task. While adding `set -euo pipefail` is generally good practice to avoid silent failures, but after further discussion there are certain scenarios where we want to be more graceful in handling outputs. When it comes specifically to ivar variant calling, if there is bad quality data, we may not necessarily want it to hard fail but report "Not computed: no variants detected" instead is reported for `ivar_variant_proportion_intermediate`, so on the users end there is a clear implication of status in the datatable. 
This PR may lead to different results in pre-existing …

[Ivar Variants] Refactor to succeed with message when no variants found

---

tasks/gene_typing/variant_detection/task_snippy_variants.wdl
tests/workflows/theiaprok/test_wf_theiaprok_illumina_pe.yml
tests/workflows/theiaprok/test_wf_theiaprok_illumina_se.yml
workflows/utilities/wf_merlin_magic.wdl

This PR closes #570 
This PR addresses the issue brought up in #570 regarding the necessary resource requirements for the `snippy_variants` task. No changes were made to memory allocation. Added error handling and minor formatting fixes.
- task_snippy_variants.wdl
- wf_merlin_magic.wdl
- wf_snippy_variants.wdl 
- wf_snippy_streamline_fasta.wdl 
- wf_snippy_streamline.wdl 
Added `set -euo pipefail` at the beginning of the command to catch potential errors and prevent silent failures.
I encountered an issue where Snippy was terminated by the system due to memory …

[Snippy Variants] Preserve current memory allocation & add error handling to prevent silent failures

---

.github/workflows/build-documentation.yml
.github/workflows/build-version-release.yml

As of today, the actions/cache@v2 dependency has been deprecated. This PR bumps this up to v4.

[Documentation] Update actions/cache version

---

docs/workflows/genomic_characterization/theiaprok.md
tasks/species_typing/vibrio/task_vibecheck_vibrio.wdl
tests/workflows/theiaprok/test_wf_theiaprok_illumina_pe.yml
tests/workflows/theiaprok/test_wf_theiaprok_illumina_se.yml
workflows/theiaprok/wf_theiaprok_illumina_pe.wdl
workflows/utilities/wf_merlin_magic.wdl

This PR adds a additional task to the _Vibrio spp._ subworkflow of TheiaProk which runs [Vibecheck](https://github.com/cholGen/Vibecheck). Vibecheck rapidly classifies _V. cholerae_ sequencing data to canonical lineages (T1-T17/AFR1-AFR17). 
- TheiaProk_Illumina_PE
- merlin_magic
This PR adds an additional task [task_vibecheck_vibrio.wdl](tasks/species_typing/vibrio/task_vibecheck_vibrio.wdl), which is called during Vibrio spp. branch of the `merlin_magic` workflow.  Therefore, the inputs, parameters, and outputs of the additional task were added to …

Adds Vibecheck to the Vibrio spp. subworkflow of TheiaProk

---

docs/workflows/genomic_characterization/freyja.md
tasks/taxon_id/freyja/task_freyja.wdl
workflows/freyja/wf_freyja_fastq.wdl

This PR closes #752 
This PR adds the functionality of --gff to task_freyja.wdl. This will populate the remaining columns of the output file to include the genomic feature that contains the mutation as well as the amino acid mutation. Along side this is a change that makes primer_bed an optional input for those who are using approaches not utilizing a primer amplicon scheme. Finally this PR is looking to incorporate Freyja v1.5.3.
- wf_freyja_fastq
- task_freyja
If pre-existing outputs are now run with --gff and the reference GFF passed there will be new mutation information present.
This PR uses an element that could cause duplicate runs to have different …

[Freyja] Add GFF flag and make primer_bed optional

---

docs/workflows/phylogenetic_construction/snippy_streamline.md
docs/workflows/phylogenetic_construction/snippy_streamline_fasta.md
workflows/phylogenetics/wf_snippy_streamline.wdl
workflows/phylogenetics/wf_snippy_streamline_fasta.wdl

This PR closes #773 
This PR adds the `use_centroid_as_reference` boolean variable that will indicate the genome identified as the centroid should be used as the reference genome in snippy_streamline and snippy_streamline_fasta.
- snippy_streamline
- snippy_streamline_fasta
This PR may lead to different results in pre-existing outputs: **Yes**, if boolean option turned on
If `use_centroid_as_reference` is true AND a reference genome has NOT been supplied, centroid WILL run but NCBI datasets will NOT be queried and a reference assembly will NOT be downloaded. Through select_first, the centroid genome will be passed to snippy_variants …

[Snippy_Streamline] use the centroid genome as the reference if indicated

---

tasks/species_typing/mycobacterium/task_tbp_parser.wdl

It is possible for `samtools depth -J` to output nothing when working with an extremely low coverage BAM file. This is less-than-ideal when this null output is piped to `awk`.
In the TBProfiler parser, $GENOME_PC is not directly affected because it pipes to `wc -l`, but $AVG_DEPTH uses a different approach, resulting in null output. Once the WDL task tries to outputs, it errors, because it cannot interpret an empty file's contents as Float. 
This PR fixes the issue, allowing WDL output delocalization to occur properly.
Only directly affects task_tbp_parser.wdl.
This PR may lead to different results in pre-existing outputs: **Yes, but in a good way**
This changes $AVG_DEPTH's awk command so it won't …

Handle edge case of extremely low coverage

---

workflows/theiaeuk/wf_theiaeuk_illumina_pe.wdl
workflows/utilities/wf_read_QC_trim_pe.wdl

This PR closes #822
Fully enables kraken2 into TheiaEuk_PE as it was unable to be run before, outlined in the linked issue.
TheiaEuk_Illumina_PE
Read_QC_Trim
Could add kraken outputs.
Enable the running of `kraken2standalone` within TheiaEuk_Illumina_PE.
Added `theiaeuk` to the conditional that controls the running of `kraken2standalone` within `read_QC_trim` as well as adding the `workflow_series = "theiaeuk"` to the call of `read_QC_trim`.
NA
This will add kraken2 outputs when call_kraken and DB are provided.
I have run TheiaEuk_Illumina_PE enabling kraken, providing …

[TheiaEuk_Illumina_PE] Add theiaeuk to kraken2 conditional and workflow series to read_QC_trim call

---

docs/assets/tables/all_inputs.tsv
docs/common_text/stxtyper_task.md
docs/workflows/genomic_characterization/theiaprok.md
tasks/species_typing/escherichia_shigella/task_stxtyper.wdl

This PR closes #817 
Updates Docker container of STXtyper to v 1.0.42 from 1.0.24.
TheiaProk Series
It may, per the release notes of STXtyper there are improvements to result differentiation.
"This version is a minor improvement to the differentiation between PARTIAL, PARTIAL_END_OF_CONTIG, and COMPLETE_NOVEL. These changes will not affect the type symbol returned and thus will have no effect on operons that are 'COMPLETE'."
[Release Page](https://github.com/ncbi/stxtyper/releases/tag/v1.0.42)
This PR uses an element that could cause duplicate runs to have different results: **Yes**
Per above, this could lead to differences in PARTIAL results within STXtyper. …

[STXtyper] Update to container version 1.0.42

---

docs/assets/tables/all_outputs.tsv
docs/common_text/skani_task.md
docs/workflows/genomic_characterization/theiaviral.md
tasks/taxon_id/task_skani.wdl
tasks/utilities/data_handling/task_parse_mapping.wdl
workflows/theiaviral/wf_theiaviral_illumina_pe.wdl
workflows/theiaviral/wf_theiaviral_ont.wdl

This PR addresses two issues, both related to masking low coverage regions in the reference genome prior to consensus generation.
- replace all ambiguous bases with "N"s
- include reads containing deletions when calculating coverage depth
- `task_parse_mapping.wdl`
- `wf_theiaviral_ont.wdl`
Ambiguous Bases
- Occasionally, reference fastas downloaded from NCBI can include ambiguous bases (e.g., "S") that are not A/C/G/T. During variant calling, Clair3 will interpret these bases as "N"s, which can lead to mismatches when comparing the reference base …

[TheiaViral] Mask Ambiguous Bases and Consider Reads with Deletions

---

docs/common_text/digger_denovo_task.md
docs/workflows/standalone/theiavalidate.md

- [Digger denovo](https://theiagen.github.io/public_health_bioinformatics/latest/common_text/digger_denovo_task) 
-  The link to wf_digger_denovo.wdl was serving 404 due to a missing "l" in ".wdl" 
- [TheiaValidate](https://theiagen.github.io/public_health_bioinformatics/latest/workflows/standalone/theiavalidate/)
- **<RANGE\>** was absent due to a missing backslash in formatting
- Exclusion criteria was living in the past

[Documentation] Fix formatting in TheiaValidate and link typo in digger_denovo
